/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package A03_SanPham;


//import java.awt.Image;
//import java.io.File;
//import java.sql.Blob;
//import javax.swing.ImageIcon;
//import javax.swing.JFileChooser;
import A00_Support.Combobox;
import A00_Connection.JDBCConnection;
import static A00_Support.IsNumeric.isNumeric;


import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author ADMIN
 */
public class AddSanPham extends javax.swing.JFrame {
    SanPhamService sanPhamService;
    SanPham sanPham;

    /**
     * Creates new form ADDHangHoa
     */
    public AddSanPham() {
        initComponents();
        sanPhamService = new SanPhamService();
        sanPham = new SanPham();
        try {
            Connection connection=JDBCConnection.getJDBCConnection();
            PreparedStatement preparedStatement = connection.prepareStatement("select * from nhacungcap");
            ResultSet resultSet = preparedStatement.executeQuery();
            while (resultSet.next())
            {
                Combobox combobox = new Combobox(resultSet.getString(1), resultSet.getString(2));
                maNCCComboBox.addItem(combobox);
            }
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        themMoiSPLabel = new javax.swing.JLabel();
        dongButton = new javax.swing.JButton();
        maSPLabel = new javax.swing.JLabel();
        tenSPLabel = new javax.swing.JLabel();
        loaiSPLabel = new javax.swing.JLabel();
        maNCCLabel = new javax.swing.JLabel();
        giaBanLabel = new javax.swing.JLabel();
        giaNhapLabel = new javax.swing.JLabel();
        soLuongLabel = new javax.swing.JLabel();
        ghiChuLabel = new javax.swing.JLabel();
        maSPTextField = new javax.swing.JTextField();
        tenSPTextField = new javax.swing.JTextField();
        loaiSPComboBox = new javax.swing.JComboBox<>();
        giaBanTextField = new javax.swing.JTextField();
        giaNhapTextField = new javax.swing.JTextField();
        soLuongTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        ghiChuTextField = new javax.swing.JTextArea();
        luuButton = new javax.swing.JButton();
        maNCCComboBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setSize(new java.awt.Dimension(700, 800));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(700, 800));

        jPanel2.setBackground(new java.awt.Color(102, 255, 0));
        jPanel2.setPreferredSize(new java.awt.Dimension(700, 80));

        themMoiSPLabel.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        themMoiSPLabel.setForeground(new java.awt.Color(51, 51, 51));
        themMoiSPLabel.setText("Thêm Mới Sản Phẩm");
        themMoiSPLabel.setPreferredSize(new java.awt.Dimension(300, 60));

        dongButton.setBackground(new java.awt.Color(102, 255, 0));
        dongButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        dongButton.setForeground(new java.awt.Color(51, 51, 51));
        dongButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/A00_Icon/Delete.png"))); // NOI18N
        dongButton.setText("Đóng");
        dongButton.setPreferredSize(new java.awt.Dimension(120, 40));
        dongButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dongButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(themMoiSPLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(dongButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(dongButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(themMoiSPLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                .addContainerGap())
        );

        maSPLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        maSPLabel.setText("Mã Sản Phẩm");
        maSPLabel.setPreferredSize(new java.awt.Dimension(170, 40));

        tenSPLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tenSPLabel.setText("Tên Sản Phẩm");
        tenSPLabel.setPreferredSize(new java.awt.Dimension(120, 40));

        loaiSPLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        loaiSPLabel.setText("Loại Sản Phẩm");
        loaiSPLabel.setPreferredSize(new java.awt.Dimension(120, 40));

        maNCCLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        maNCCLabel.setText("Mã Nhà Cung Cấp");
        maNCCLabel.setPreferredSize(new java.awt.Dimension(170, 40));

        giaBanLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        giaBanLabel.setText("Giá Bán");
        giaBanLabel.setPreferredSize(new java.awt.Dimension(120, 40));

        giaNhapLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        giaNhapLabel.setText("Giá Nhập");
        giaNhapLabel.setPreferredSize(new java.awt.Dimension(120, 40));

        soLuongLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        soLuongLabel.setText("Số Lượng");
        soLuongLabel.setPreferredSize(new java.awt.Dimension(120, 40));

        ghiChuLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ghiChuLabel.setText("Ghi Chú");
        ghiChuLabel.setPreferredSize(new java.awt.Dimension(120, 40));

        maSPTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        maSPTextField.setPreferredSize(new java.awt.Dimension(450, 40));

        tenSPTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tenSPTextField.setPreferredSize(new java.awt.Dimension(450, 40));

        loaiSPComboBox.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        loaiSPComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sữa", "Bánh Kẹo", "Hóa Mỹ Phẩm", "Nước Giải Khát", "Rượu", "Bia", "Gia Vị", "Thuốc Lá", "Giấy", "Đồ Ăn Liền", "Đồ Hộp", "Thẻ Cào", "Văn Phòng Phẩm" }));
        loaiSPComboBox.setPreferredSize(new java.awt.Dimension(250, 40));

        giaBanTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        giaBanTextField.setPreferredSize(new java.awt.Dimension(450, 40));

        giaNhapTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        giaNhapTextField.setPreferredSize(new java.awt.Dimension(450, 40));

        soLuongTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        soLuongTextField.setPreferredSize(new java.awt.Dimension(450, 40));

        ghiChuTextField.setColumns(20);
        ghiChuTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ghiChuTextField.setRows(5);
        jScrollPane1.setViewportView(ghiChuTextField);

        luuButton.setBackground(new java.awt.Color(102, 255, 0));
        luuButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        luuButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/A00_Icon/Save.png"))); // NOI18N
        luuButton.setText("Lưu");
        luuButton.setPreferredSize(new java.awt.Dimension(120, 40));
        luuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                luuButtonActionPerformed(evt);
            }
        });

        maNCCComboBox.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        maNCCComboBox.setPreferredSize(new java.awt.Dimension(250, 40));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 35, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(maNCCLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(giaNhapLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(maNCCComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(giaNhapTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(giaBanTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(soLuongTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(giaBanLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(maSPLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tenSPLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(loaiSPLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(maSPTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(loaiSPComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tenSPTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(soLuongLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ghiChuLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 698, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(285, 285, 285)
                .addComponent(luuButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maSPLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maSPTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tenSPLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tenSPTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loaiSPLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loaiSPComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maNCCLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maNCCComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(giaNhapLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(giaNhapTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(giaBanLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(giaBanTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(soLuongLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(soLuongTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ghiChuLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(luuButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void luuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_luuButtonActionPerformed
        // TODO add your handling code here:
        if (maSPTextField.getText().isEmpty()||tenSPTextField.getText().isEmpty()) 
        {
            JOptionPane.showMessageDialog(this, "Vui lòng điền đầy đủ Mã và Tên Sản Phẩm");
        }
        else
        {
            int i= sanPhamService.getCountMASP(maSPTextField.getText());
            if (i!=0)
            {
                JOptionPane.showMessageDialog(this, "Mã Sản Phẩm này đã tồn tại");
            }
            else
            {
                if (!isNumeric(giaNhapTextField.getText().toString())||!isNumeric(giaBanTextField.getText().toString())||!isNumeric(soLuongTextField.getText().toString()))
                        
                {
                    JOptionPane.showMessageDialog(this, "Giá Bán, Giá Nhập, Số Lượng phải nhập định dạng số");
                }
                else
                {      
                    sanPham.setMASP(maSPTextField.getText());
                    sanPham.setTENSP(tenSPTextField.getText());
                    String loaiSP = String.valueOf(loaiSPComboBox.getSelectedItem());
                    sanPham.setLOAISP(loaiSP);
                    Combobox combobox = (Combobox) maNCCComboBox.getSelectedItem();
                    sanPham.setMANCC(combobox.getId());
                    if (giaNhapTextField.getText().toString().equals("")) sanPham.setGIANHAP(Double.valueOf("0"));
                    else sanPham.setGIANHAP(Double.valueOf(giaNhapTextField.getText()));
                    if (giaBanTextField.getText().toString().equals("")) sanPham.setGIABAN(Double.valueOf("0"));
                    else sanPham.setGIABAN(Double.valueOf(giaBanTextField.getText()));
                    if (soLuongTextField.getText().toString().equals("")) sanPham.setSOLUONG(Integer.valueOf("0"));
                    else sanPham.setSOLUONG(Integer.valueOf(soLuongTextField.getText()));
                    sanPham.setGHICHU(ghiChuTextField.getText());           
                    sanPhamService.addSanPham(sanPham);    
                    JOptionPane.showMessageDialog(this, "Lưu thành công!");
                }    
            }
        }
    }//GEN-LAST:event_luuButtonActionPerformed

    private void dongButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dongButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_dongButtonActionPerformed
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddSanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddSanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddSanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddSanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddSanPham().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton dongButton;
    private javax.swing.JLabel ghiChuLabel;
    private javax.swing.JTextArea ghiChuTextField;
    private javax.swing.JLabel giaBanLabel;
    private javax.swing.JTextField giaBanTextField;
    private javax.swing.JLabel giaNhapLabel;
    private javax.swing.JTextField giaNhapTextField;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> loaiSPComboBox;
    private javax.swing.JLabel loaiSPLabel;
    private javax.swing.JButton luuButton;
    private javax.swing.JComboBox<Combobox> maNCCComboBox;
    private javax.swing.JLabel maNCCLabel;
    private javax.swing.JLabel maSPLabel;
    private javax.swing.JTextField maSPTextField;
    private javax.swing.JLabel soLuongLabel;
    private javax.swing.JTextField soLuongTextField;
    private javax.swing.JLabel tenSPLabel;
    private javax.swing.JTextField tenSPTextField;
    private javax.swing.JLabel themMoiSPLabel;
    // End of variables declaration//GEN-END:variables
}
