/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package A03_SanPham;

import A00_Support.Combobox;
import A00_Connection.JDBCConnection;
import static A00_Support.IsNumeric.isNumeric;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

import javax.swing.JOptionPane;


/**
 *
 * @author ADMIN
 */
public class EditSanPham extends javax.swing.JFrame {  
    private SanPham sanPham;
    SanPhamService sanPhamService;
    String MASPdangsua;
    /**
     * Creates new form ADDHangHoa
     */
    public EditSanPham(String MASP) {
        sanPham = new SanPham();
        sanPhamService = new SanPhamService();
        sanPham = sanPhamService.getSanPhamByMASP(MASP);
        initComponents();
        try {
            Connection connection=JDBCConnection.getJDBCConnection();
            PreparedStatement preparedStatement = connection.prepareStatement("select * from nhacungcap");
            ResultSet resultSet = preparedStatement.executeQuery();
            while (resultSet.next())
            {
                Combobox combobox = new Combobox(resultSet.getString(1), resultSet.getString(2));
                maNCCComboBox.addItem(combobox);
            }
        } catch (Exception e) {
        }  
       
        for (int i=0;i<maNCCComboBox.getItemCount();i++)
        {
            Combobox combobox = (Combobox)maNCCComboBox.getItemAt(i);
            if (combobox.getId().equals(sanPham.getMANCC()))
            {    
                maNCCComboBox.setSelectedItem(combobox);
                break;
            }
            
        }
        MASPdangsua=sanPham.getMASP();
        maSPTextField.setText(sanPham.getMASP());
        tenSPTextField.setText(sanPham.getTENSP());
        //maNCCTextField.setText(sanPham.getMANCC());
        String loaiSP = sanPham.getLOAISP();
        loaiSPComboBox.setSelectedItem(loaiSP);
        giaNhapTextField.setText(sanPham.getGIANHAP().toString());
        giaBanTextField.setText(sanPham.getGIABAN().toString());
        soLuongTextField.setText(String.valueOf(sanPham.getSOLUONG()));
        ghiChuTextField.setText(sanPham.getGHICHU());
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        chinhSuaSPLabel = new javax.swing.JLabel();
        dongButton = new javax.swing.JButton();
        maSPLabel = new javax.swing.JLabel();
        tenSPLabel = new javax.swing.JLabel();
        loaiSPLabel = new javax.swing.JLabel();
        maNCCLabel = new javax.swing.JLabel();
        giaBanLabel = new javax.swing.JLabel();
        giaNhapLabel = new javax.swing.JLabel();
        soLuongLabel = new javax.swing.JLabel();
        ghiChuLabel = new javax.swing.JLabel();
        maSPTextField = new javax.swing.JTextField();
        tenSPTextField = new javax.swing.JTextField();
        loaiSPComboBox = new javax.swing.JComboBox<>();
        giaBanTextField = new javax.swing.JTextField();
        giaNhapTextField = new javax.swing.JTextField();
        soLuongTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        ghiChuTextField = new javax.swing.JTextArea();
        luuButton = new javax.swing.JButton();
        maNCCComboBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(700, 800));
        setSize(new java.awt.Dimension(700, 800));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setPreferredSize(new java.awt.Dimension(700, 800));

        jPanel2.setBackground(new java.awt.Color(102, 255, 0));
        jPanel2.setPreferredSize(new java.awt.Dimension(700, 80));

        chinhSuaSPLabel.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        chinhSuaSPLabel.setForeground(new java.awt.Color(51, 51, 51));
        chinhSuaSPLabel.setText("Chỉnh Sửa Sản Phẩm");
        chinhSuaSPLabel.setPreferredSize(new java.awt.Dimension(300, 60));

        dongButton.setBackground(new java.awt.Color(102, 255, 0));
        dongButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        dongButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/A00_Icon/Delete.png"))); // NOI18N
        dongButton.setText("Đóng");
        dongButton.setPreferredSize(new java.awt.Dimension(120, 40));
        dongButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dongButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(chinhSuaSPLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addComponent(dongButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(dongButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(chinhSuaSPLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE))
                .addContainerGap())
        );

        maSPLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        maSPLabel.setText("Mã Sản Phẩm");
        maSPLabel.setPreferredSize(new java.awt.Dimension(170, 40));

        tenSPLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tenSPLabel.setText("Tên Sản Phẩm");
        tenSPLabel.setPreferredSize(new java.awt.Dimension(170, 40));

        loaiSPLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        loaiSPLabel.setText("Loại Sản Phẩm");
        loaiSPLabel.setPreferredSize(new java.awt.Dimension(170, 40));

        maNCCLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        maNCCLabel.setText("Mã Nhà Cung Cấp");
        maNCCLabel.setPreferredSize(new java.awt.Dimension(170, 40));

        giaBanLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        giaBanLabel.setText("Giá Bán");
        giaBanLabel.setPreferredSize(new java.awt.Dimension(170, 40));

        giaNhapLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        giaNhapLabel.setText("Giá Nhập");
        giaNhapLabel.setPreferredSize(new java.awt.Dimension(170, 40));

        soLuongLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        soLuongLabel.setText("Số Lượng");
        soLuongLabel.setPreferredSize(new java.awt.Dimension(170, 40));

        ghiChuLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ghiChuLabel.setText("Ghi Chú");
        ghiChuLabel.setPreferredSize(new java.awt.Dimension(170, 40));

        maSPTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        maSPTextField.setPreferredSize(new java.awt.Dimension(450, 40));

        tenSPTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tenSPTextField.setPreferredSize(new java.awt.Dimension(450, 40));

        loaiSPComboBox.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        loaiSPComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sữa", "Bánh Kẹo", "Hóa Mỹ Phẩm", "Nước Giải Khát", "Rượu", "Bia", "Gia Vị", "Thuốc Lá", "Giấy", "Đồ Ăn Liền", "Đồ Hộp", "Thẻ Cào", "Văn Phòng Phẩm" }));
        loaiSPComboBox.setPreferredSize(new java.awt.Dimension(250, 40));

        giaBanTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        giaBanTextField.setPreferredSize(new java.awt.Dimension(450, 40));

        giaNhapTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        giaNhapTextField.setPreferredSize(new java.awt.Dimension(450, 40));

        soLuongTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        soLuongTextField.setPreferredSize(new java.awt.Dimension(450, 40));

        ghiChuTextField.setColumns(20);
        ghiChuTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ghiChuTextField.setRows(5);
        jScrollPane1.setViewportView(ghiChuTextField);

        luuButton.setBackground(new java.awt.Color(102, 255, 0));
        luuButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        luuButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/A00_Icon/Save.png"))); // NOI18N
        luuButton.setText("Lưu");
        luuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                luuButtonActionPerformed(evt);
            }
        });

        maNCCComboBox.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        maNCCComboBox.setPreferredSize(new java.awt.Dimension(250, 40));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(300, 300, 300)
                        .addComponent(luuButton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(giaNhapLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(giaBanLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(giaNhapTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(giaBanTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(soLuongLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(soLuongTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(maSPLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(maSPTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(tenSPLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tenSPTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(maNCCLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(loaiSPLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(loaiSPComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(maNCCComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(ghiChuLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(21, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 698, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maSPLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maSPTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tenSPLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tenSPTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maNCCLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maNCCComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loaiSPLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loaiSPComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(giaNhapLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(giaNhapTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(giaBanLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(giaBanTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(soLuongLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(soLuongTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ghiChuLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(luuButton)
                .addGap(6, 6, 6))
        );

        soLuongLabel.getAccessibleContext().setAccessibleName("Số Lượng");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void dongButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dongButtonActionPerformed
        // TODO add your handling code here:
        
        this.dispose();
    }//GEN-LAST:event_dongButtonActionPerformed

    private void luuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_luuButtonActionPerformed
        // TODO add your handling code here:
        if (maSPTextField.getText().isEmpty()||tenSPTextField.getText().isEmpty()) 
        {
            JOptionPane.showMessageDialog(this, "Vui lòng điền đầy đủ Mã và Tên Sản Phẩm");
        }
        else
        {
            int i= sanPhamService.getCountMASP(maSPTextField.getText());
            if (i!=0 && !MASPdangsua.equals(maSPTextField.getText()))
            {
                JOptionPane.showMessageDialog(this, "Mã Sản Phẩm bị trùng lặp");
                maSPTextField.setText(MASPdangsua);
            }
            else
            {
                if (!isNumeric(giaNhapTextField.getText().toString())||!isNumeric(giaBanTextField.getText().toString())||!isNumeric(soLuongTextField.getText().toString()))
                        
                {
                    JOptionPane.showMessageDialog(this, "Giá Bán, Giá Nhập, Số Lượng phải nhập định dạng số");
                }
                else
                {
                    sanPham.setMASP(maSPTextField.getText());
                    sanPham.setTENSP(tenSPTextField.getText());
                    Combobox combobox = (Combobox) maNCCComboBox.getSelectedItem();
                    sanPham.setMANCC(combobox.getId());
                    String loaiSP = String.valueOf(loaiSPComboBox.getSelectedItem());
                    sanPham.setLOAISP(loaiSP);     
                    sanPham.setGIANHAP(Double.valueOf(giaNhapTextField.getText()));
                    sanPham.setGIABAN(Double.valueOf(giaBanTextField.getText()));       
                    sanPham.setSOLUONG(Integer.valueOf(soLuongTextField.getText()));
                    sanPham.setGHICHU(ghiChuTextField.getText());

                    sanPhamService.updateSanPham(sanPham);
                    JOptionPane.showMessageDialog(this, "Lưu thành công!"); 
                }
            }
        }   
    }//GEN-LAST:event_luuButtonActionPerformed
    
    
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel chinhSuaSPLabel;
    private javax.swing.JButton dongButton;
    private javax.swing.JLabel ghiChuLabel;
    private javax.swing.JTextArea ghiChuTextField;
    private javax.swing.JLabel giaBanLabel;
    private javax.swing.JTextField giaBanTextField;
    private javax.swing.JLabel giaNhapLabel;
    private javax.swing.JTextField giaNhapTextField;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> loaiSPComboBox;
    private javax.swing.JLabel loaiSPLabel;
    private javax.swing.JButton luuButton;
    private javax.swing.JComboBox<Combobox> maNCCComboBox;
    private javax.swing.JLabel maNCCLabel;
    private javax.swing.JLabel maSPLabel;
    private javax.swing.JTextField maSPTextField;
    private javax.swing.JLabel soLuongLabel;
    private javax.swing.JTextField soLuongTextField;
    private javax.swing.JLabel tenSPLabel;
    private javax.swing.JTextField tenSPTextField;
    // End of variables declaration//GEN-END:variables

    
}
