/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package A03_SanPham;

import A01_DangNhap.FormDangNhap;
import A11_BaoCao.FormBaoCao;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import A00_Connection.JDBCConnection;
import A07_HoaDon.FormHoaDon;
import A05_KhachHang.FormKhachHang;
import A06_NhaCungCap.FormNhaCungCap;
import A04_NhanVien.FormNhanVien;
import A09_DonNhapHang.FormDonNhapHang;
import java.awt.Font;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author ADMIN
 */
public class FormSanPham extends javax.swing.JFrame {
    SanPhamService sanPhamService;
    DefaultTableModel defaultTableModel;

    /**
     * Creates new form SanPham
     */
    public FormSanPham() {
        initComponents();
        sanPhamService = new SanPhamService();
        defaultTableModel = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; //To change body of generated methods, choose Tools | Templates.
            }
            
        };
        sanPhamTable.setModel(defaultTableModel);
        defaultTableModel.addColumn("Mã Sản Phẩm");
        defaultTableModel.addColumn("Tên Sản Phẩm");
        defaultTableModel.addColumn("Mã Nhà Cung Cấp");
        defaultTableModel.addColumn("Loại Sản Phẩm");
        defaultTableModel.addColumn("Giá Nhập");
        defaultTableModel.addColumn("Giá Bán");
        defaultTableModel.addColumn("Số Lượng");
        defaultTableModel.addColumn("Ghi Chú");
        sanPhamTable.setRowHeight(24);
        sanPhamTable.setFont(new Font("Segoe UI",Font.PLAIN,18));
        sanPhamTable.getTableHeader().setFont(new Font("Segoe",Font.BOLD,18));
        sanPhamTable.getColumnModel().getColumn(2).setPreferredWidth(100);
        setTableData(sanPhamService.getAllHangHoas());
       
    }
    private void setTableData(List<SanPham> sanPhams){
        for(SanPham sanPham : sanPhams){
            defaultTableModel.addRow(new Object[]{sanPham.getMASP(), sanPham.getTENSP(),sanPham.getMANCC(), sanPham.getLOAISP(),
            sanPham.getGIANHAP(), sanPham.getGIABAN(), sanPham.getSOLUONG(), sanPham.getGHICHU()});                  
        }
    }
   
    private void Sapxep(String jQuery){
        try {           
            Connection Con = JDBCConnection.getJDBCConnection();
            PreparedStatement Pst = Con.prepareStatement(jQuery);
            ResultSet Rs = Pst.executeQuery();
            defaultTableModel.setRowCount(0);
            while (Rs.next()) {
                Object objList[] = {Rs.getString("MASP"), Rs.getString("TENSP"), Rs.getString("MANCC"), Rs.getString("LOAISP"), Rs.getDouble("GIANHAP"), Rs.getDouble("GIABAN"),Rs.getInt("SOLUONG"),Rs.getString("GHICHU")};
                defaultTableModel.addRow(objList);                
            }
        } catch (SQLException ex) {
            Logger.getLogger(FormHoaDon.class.getName()).log(Level.SEVERE,null,ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel3 = new javax.swing.JPanel();
        sanPhamLabel = new javax.swing.JLabel();
        themMoiButton = new javax.swing.JButton();
        timKiemTextField = new javax.swing.JTextField();
        xoaButton = new javax.swing.JButton();
        suaButton = new javax.swing.JButton();
        refreshButton = new javax.swing.JButton();
        timKiemLabel = new javax.swing.JLabel();
        loaiSPComboBox = new javax.swing.JComboBox<>();
        loaiSPLabel = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        nhanVienButton = new javax.swing.JButton();
        nhapHangButton = new javax.swing.JButton();
        nhaCungCapButton = new javax.swing.JButton();
        baoCaoButton = new javax.swing.JButton();
        khachHangButton = new javax.swing.JButton();
        dangXuatButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        hoaDonButton = new javax.swing.JButton();
        sapXepTheoLabel = new javax.swing.JLabel();
        giamDanButton = new javax.swing.JButton();
        tangDanButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        sanPhamTable = new javax.swing.JTable();
        soLuongLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setSize(new java.awt.Dimension(1508, 668));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setPreferredSize(new java.awt.Dimension(1508, 668));

        sanPhamLabel.setBackground(new java.awt.Color(60, 63, 100));
        sanPhamLabel.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        sanPhamLabel.setForeground(new java.awt.Color(51, 51, 51));
        sanPhamLabel.setText("Sản Phẩm");
        sanPhamLabel.setPreferredSize(new java.awt.Dimension(120, 40));

        themMoiButton.setBackground(new java.awt.Color(102, 255, 0));
        themMoiButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        themMoiButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/A00_Icon/Add.png"))); // NOI18N
        themMoiButton.setText("Thêm");
        themMoiButton.setPreferredSize(new java.awt.Dimension(120, 40));
        themMoiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themMoiButtonActionPerformed(evt);
            }
        });

        timKiemTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        timKiemTextField.setPreferredSize(new java.awt.Dimension(350, 40));
        timKiemTextField.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                timKiemTextFieldCaretUpdate(evt);
            }
        });
        timKiemTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timKiemTextFieldActionPerformed(evt);
            }
        });

        xoaButton.setBackground(new java.awt.Color(102, 255, 0));
        xoaButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        xoaButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/A00_Icon/icons8-delete-bin-32.png"))); // NOI18N
        xoaButton.setText("Xóa");
        xoaButton.setPreferredSize(new java.awt.Dimension(120, 40));
        xoaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xoaButtonActionPerformed(evt);
            }
        });

        suaButton.setBackground(new java.awt.Color(102, 255, 0));
        suaButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        suaButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/A00_Icon/Edit.png"))); // NOI18N
        suaButton.setText("Sửa");
        suaButton.setPreferredSize(new java.awt.Dimension(120, 40));
        suaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suaButtonActionPerformed(evt);
            }
        });

        refreshButton.setBackground(new java.awt.Color(102, 255, 0));
        refreshButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        refreshButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/A00_Icon/Refresh.png"))); // NOI18N
        refreshButton.setText("Refresh");
        refreshButton.setPreferredSize(new java.awt.Dimension(120, 40));
        refreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshButtonActionPerformed(evt);
            }
        });

        timKiemLabel.setBackground(new java.awt.Color(204, 204, 255));
        timKiemLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        timKiemLabel.setText("Tìm kiếm");
        timKiemLabel.setPreferredSize(new java.awt.Dimension(80, 40));

        loaiSPComboBox.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        loaiSPComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tất Cả", "Sữa", "Bánh Kẹo", "Hóa Mỹ Phẩm", "Nước Giải Khát", "Rượu", "Bia", "Gia Vị", "Thuốc Lá", "Giấy", "Đồ Ăn Liền", "Đồ Hộp", "Thẻ Cào", "Văn Phòng Phẩm", " " }));
        loaiSPComboBox.setPreferredSize(new java.awt.Dimension(170, 40));
        loaiSPComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                loaiSPComboBoxItemStateChanged(evt);
            }
        });

        loaiSPLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        loaiSPLabel.setText("Loại Sản Phẩm");
        loaiSPLabel.setPreferredSize(new java.awt.Dimension(120, 30));

        jPanel8.setBackground(new java.awt.Color(102, 255, 0));
        jPanel8.setPreferredSize(new java.awt.Dimension(1506, 80));

        nhanVienButton.setBackground(new java.awt.Color(102, 255, 102));
        nhanVienButton.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        nhanVienButton.setForeground(new java.awt.Color(51, 51, 51));
        nhanVienButton.setText("Nhân Viên");
        nhanVienButton.setPreferredSize(new java.awt.Dimension(170, 50));
        nhanVienButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nhanVienButtonActionPerformed(evt);
            }
        });

        nhapHangButton.setBackground(new java.awt.Color(102, 255, 102));
        nhapHangButton.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        nhapHangButton.setForeground(new java.awt.Color(51, 51, 51));
        nhapHangButton.setText("Nhập Hàng");
        nhapHangButton.setPreferredSize(new java.awt.Dimension(170, 50));
        nhapHangButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nhapHangButtonActionPerformed(evt);
            }
        });

        nhaCungCapButton.setBackground(new java.awt.Color(102, 255, 102));
        nhaCungCapButton.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        nhaCungCapButton.setForeground(new java.awt.Color(51, 51, 51));
        nhaCungCapButton.setText("Nhà Cung Cấp");
        nhaCungCapButton.setPreferredSize(new java.awt.Dimension(170, 50));
        nhaCungCapButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nhaCungCapButtonActionPerformed(evt);
            }
        });

        baoCaoButton.setBackground(new java.awt.Color(102, 255, 102));
        baoCaoButton.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        baoCaoButton.setForeground(new java.awt.Color(51, 51, 51));
        baoCaoButton.setText("Báo Cáo");
        baoCaoButton.setPreferredSize(new java.awt.Dimension(170, 50));
        baoCaoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baoCaoButtonActionPerformed(evt);
            }
        });

        khachHangButton.setBackground(new java.awt.Color(102, 255, 102));
        khachHangButton.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        khachHangButton.setForeground(new java.awt.Color(51, 51, 51));
        khachHangButton.setText("Khách Hàng");
        khachHangButton.setPreferredSize(new java.awt.Dimension(170, 50));
        khachHangButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                khachHangButtonActionPerformed(evt);
            }
        });

        dangXuatButton.setBackground(new java.awt.Color(102, 255, 102));
        dangXuatButton.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        dangXuatButton.setForeground(new java.awt.Color(51, 51, 51));
        dangXuatButton.setText("Đăng Xuất");
        dangXuatButton.setPreferredSize(new java.awt.Dimension(170, 50));
        dangXuatButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dangXuatButtonActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jButton1.setText("Sản Phẩm");
        jButton1.setPreferredSize(new java.awt.Dimension(170, 50));

        hoaDonButton.setBackground(new java.awt.Color(102, 255, 102));
        hoaDonButton.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        hoaDonButton.setForeground(new java.awt.Color(51, 51, 51));
        hoaDonButton.setText("Hóa Đơn");
        hoaDonButton.setPreferredSize(new java.awt.Dimension(170, 50));
        hoaDonButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hoaDonButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(nhanVienButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(khachHangButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(hoaDonButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(nhaCungCapButton, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(nhapHangButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(baoCaoButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(dangXuatButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(dangXuatButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(baoCaoButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(nhanVienButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(khachHangButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(hoaDonButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(nhaCungCapButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(nhapHangButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        sapXepTheoLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        sapXepTheoLabel.setText("Sắp Xếp Theo ");
        sapXepTheoLabel.setPreferredSize(new java.awt.Dimension(120, 30));

        giamDanButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        giamDanButton.setText("Giảm Dần");
        giamDanButton.setPreferredSize(new java.awt.Dimension(120, 40));
        giamDanButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                giamDanButtonMouseClicked(evt);
            }
        });

        tangDanButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tangDanButton.setText("Tăng Dần");
        tangDanButton.setPreferredSize(new java.awt.Dimension(120, 40));
        tangDanButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tangDanButtonMouseClicked(evt);
            }
        });

        sanPhamTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        sanPhamTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(sanPhamTable);

        soLuongLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        soLuongLabel.setText("Số Lượng");
        soLuongLabel.setPreferredSize(new java.awt.Dimension(120, 30));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sanPhamLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loaiSPLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loaiSPComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sapXepTheoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(giamDanButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(tangDanButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(soLuongLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(suaButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(refreshButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(timKiemLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(timKiemTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(themMoiButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(xoaButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(sanPhamLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(timKiemTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(timKiemLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(themMoiButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(xoaButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(loaiSPLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(loaiSPComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(sapXepTheoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(soLuongLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tangDanButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(giamDanButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(refreshButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(suaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void themMoiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_themMoiButtonActionPerformed
        // TODO add your handling code here:
        new AddSanPham().setVisible(true);
    }//GEN-LAST:event_themMoiButtonActionPerformed

    private void timKiemTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timKiemTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_timKiemTextFieldActionPerformed

    private void xoaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xoaButtonActionPerformed
        // TODO add your handling code here:
        int row = sanPhamTable.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(FormSanPham.this, "Vui lòng chọn Sản Phẩm cần xóa","Lỗi", JOptionPane.ERROR_MESSAGE);
        }else{
            int confirm = JOptionPane.showConfirmDialog(FormSanPham.this, "Bạn chắc chắn muốn xóa không?");
            
            if (confirm == JOptionPane.YES_OPTION) {
                String MASP = String.valueOf(sanPhamTable.getValueAt(row, 0));
                
                sanPhamService.deleteSanPham(MASP);
                
                defaultTableModel.setRowCount(0);
                setTableData(sanPhamService.getAllHangHoas());
            }
        }
            
    }//GEN-LAST:event_xoaButtonActionPerformed

    private void suaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suaButtonActionPerformed
        // TODO add your handling code here:
        int row = sanPhamTable.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(FormSanPham.this, "Vui lòng chọn Sản Phẩm cần sửa","Lỗi", JOptionPane.ERROR_MESSAGE);
        }else{                      
            String MASP  = String.valueOf( sanPhamTable.getValueAt(row, 0));
                
            new EditSanPham(MASP).setVisible(true);
            
        }
    }//GEN-LAST:event_suaButtonActionPerformed

    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed
        // TODO add your handling code here:
        defaultTableModel.setRowCount(0);
        setTableData(sanPhamService.getAllHangHoas());
    }//GEN-LAST:event_refreshButtonActionPerformed

    private void timKiemTextFieldCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_timKiemTextFieldCaretUpdate
        // TODO add your handling code here:
        try {     
            if (loaiSPComboBox.getSelectedItem()=="Tất Cả") {
            Connection Con = JDBCConnection.getJDBCConnection();
            PreparedStatement Pst = Con.prepareStatement("select * from sanpham where MASP like N'%"+timKiemTextField.getText()+"%'or TENSP like N'%"+timKiemTextField.getText()+"%'");
            ResultSet Rs = Pst.executeQuery();
            defaultTableModel.setRowCount(0);
            while (Rs.next()) {
                Object objList[] = {Rs.getString("MASP"), Rs.getString("TENSP"), Rs.getString("MANCC"), Rs.getString("LOAISP"), Rs.getDouble("GIANHAP"), Rs.getDouble("GIABAN"),Rs.getInt("SOLUONG"),Rs.getString("GHICHU")};
                defaultTableModel.addRow(objList);                
            }
            }
            else
            {
                Connection Con = JDBCConnection.getJDBCConnection();
                PreparedStatement Pst = Con.prepareStatement("select * from sanpham where (MASP like N'%"+timKiemTextField.getText()+"%'or TENSP like N'%"+timKiemTextField.getText()+"%') and LOAISP like N'%"+loaiSPComboBox.getSelectedItem().toString()+"%'");
                ResultSet Rs = Pst.executeQuery();
                defaultTableModel.setRowCount(0);
                while (Rs.next()) {
                Object objList[] = {Rs.getString("MASP"), Rs.getString("TENSP"), Rs.getString("MANCC"), Rs.getString("LOAISP"), Rs.getDouble("GIANHAP"), Rs.getDouble("GIABAN"),Rs.getInt("SOLUONG"),Rs.getString("GHICHU")};
                defaultTableModel.addRow(objList);                
            }
                
            }
        } catch (SQLException ex) {
            Logger.getLogger(FormSanPham.class.getName()).log(Level.SEVERE,null,ex);
        }
    }//GEN-LAST:event_timKiemTextFieldCaretUpdate

    private void loaiSPComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_loaiSPComboBoxItemStateChanged
        // TODO add your handling code here:
        if (loaiSPComboBox.getSelectedItem()=="Tất Cả") {
                defaultTableModel.setRowCount(0);
                setTableData(sanPhamService.getAllHangHoas());
            }else{
            //select = LoaiHHCbx.getSelectedItem().toString();
            try {           
            Connection Con = JDBCConnection.getJDBCConnection();
            PreparedStatement Pst = Con.prepareStatement("select * from sanpham where (MASP like N'%"+timKiemTextField.getText()+"%'or TENSP like N'%"+timKiemTextField.getText()+"%') and LOAISP like N'%"+loaiSPComboBox.getSelectedItem().toString()+"%' ORDER BY SOLUONG DESC");
            ResultSet Rs = Pst.executeQuery();
            defaultTableModel = (DefaultTableModel)sanPhamTable.getModel();
            defaultTableModel.setRowCount(0);
            while (Rs.next()) {
                Object objList[] = {Rs.getString("MASP"), Rs.getString("TENSP"), Rs.getString("MANCC"), Rs.getString("LOAISP"), Rs.getDouble("GIANHAP"), Rs.getDouble("GIABAN"),Rs.getInt("SOLUONG"),Rs.getString("GHICHU")};
                defaultTableModel.addRow(objList);                
            }
        } catch (SQLException ex) {
            Logger.getLogger(FormSanPham.class.getName()).log(Level.SEVERE,null,ex);
        }
        }
    }//GEN-LAST:event_loaiSPComboBoxItemStateChanged

    private void nhanVienButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nhanVienButtonActionPerformed
        // TODO add your handling code here:
        new FormNhanVien().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_nhanVienButtonActionPerformed

    private void hoaDonButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hoaDonButtonActionPerformed
        // TODO add your handling code here:
        new FormHoaDon().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_hoaDonButtonActionPerformed

    private void nhapHangButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nhapHangButtonActionPerformed
        // TODO add your handling code here:
        new FormDonNhapHang().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_nhapHangButtonActionPerformed

    private void nhaCungCapButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nhaCungCapButtonActionPerformed
        // TODO add your handling code here:
        new FormNhaCungCap().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_nhaCungCapButtonActionPerformed

    private void khachHangButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_khachHangButtonActionPerformed
        // TODO add your handling code here:
        new FormKhachHang().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_khachHangButtonActionPerformed

    private void dangXuatButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dangXuatButtonActionPerformed
        // TODO add your handling code here:
        new FormDangNhap().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_dangXuatButtonActionPerformed

    private void baoCaoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baoCaoButtonActionPerformed
        // TODO add your handling code here:
        new FormBaoCao().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_baoCaoButtonActionPerformed

    private void giamDanButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_giamDanButtonMouseClicked
        // TODO add your handling code here:
        String jQuery;
        if (loaiSPComboBox.getSelectedItem().toString()=="Tất Cả")
        {
            jQuery = "select * from sanpham ORDER BY SOLUONG DESC ";
            Sapxep(jQuery);
        }
        else{
            jQuery = "select * from sanpham where LOAISP like N'"+loaiSPComboBox.getSelectedItem().toString()+"' ORDER BY SOLUONG DESC ";
            Sapxep(jQuery);
        }
    }//GEN-LAST:event_giamDanButtonMouseClicked

    private void tangDanButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tangDanButtonMouseClicked
        // TODO add your handling code here:
        String jQuery;
        if (loaiSPComboBox.getSelectedItem().toString()=="Tất Cả")
        {
            jQuery = "select * from sanpham ORDER BY SOLUONG ASC ";
            Sapxep(jQuery);
        }
        else{
            jQuery = "select * from sanpham where LOAISP like N'"+loaiSPComboBox.getSelectedItem().toString()+"' ORDER BY SOLUONG ASC ";
            Sapxep(jQuery);
        }
        
    }//GEN-LAST:event_tangDanButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormSanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormSanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormSanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormSanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormSanPham().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton baoCaoButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton dangXuatButton;
    private javax.swing.JButton giamDanButton;
    private javax.swing.JButton hoaDonButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton khachHangButton;
    private javax.swing.JComboBox<String> loaiSPComboBox;
    private javax.swing.JLabel loaiSPLabel;
    private javax.swing.JButton nhaCungCapButton;
    private javax.swing.JButton nhanVienButton;
    private javax.swing.JButton nhapHangButton;
    private javax.swing.JButton refreshButton;
    private javax.swing.JLabel sanPhamLabel;
    private javax.swing.JTable sanPhamTable;
    private javax.swing.JLabel sapXepTheoLabel;
    private javax.swing.JLabel soLuongLabel;
    private javax.swing.JButton suaButton;
    private javax.swing.JButton tangDanButton;
    private javax.swing.JButton themMoiButton;
    private javax.swing.JLabel timKiemLabel;
    private javax.swing.JTextField timKiemTextField;
    private javax.swing.JButton xoaButton;
    // End of variables declaration//GEN-END:variables
}
