/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package A04_NhanVien;

import static A00_Support.DateValidation.dateValidation;
import javax.swing.JOptionPane;

/**
 *
 * @author ADMIN
 */
public class AddNhanVien extends javax.swing.JFrame {
    NhanVienService nhanVienService;
    NhanVien nhanVien;
    

    /**
     * Creates new form FormNhanVien
     */
    public AddNhanVien() {
        initComponents();
        nhanVienService = new NhanVienService();
        nhanVien = new NhanVien();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        luuButton = new javax.swing.JButton();
        namRadioButton = new javax.swing.JRadioButton();
        maNVTextField = new javax.swing.JTextField();
        nuRadioButton = new javax.swing.JRadioButton();
        ngaySinhLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ghiChuTextField = new javax.swing.JTextArea();
        sdtLabel = new javax.swing.JLabel();
        maNVLabel = new javax.swing.JLabel();
        tenNVTextField = new javax.swing.JTextField();
        chucDanhLabel = new javax.swing.JLabel();
        ngaySinhTextField = new javax.swing.JTextField();
        gioiTinhLabel = new javax.swing.JLabel();
        jPanelTop = new javax.swing.JPanel();
        themNhanVienLabel = new javax.swing.JLabel();
        dongButton = new javax.swing.JButton();
        cmndLabel = new javax.swing.JLabel();
        tenNVLabel = new javax.swing.JLabel();
        ghiChuLabel = new javax.swing.JLabel();
        cmndTextField = new javax.swing.JTextField();
        chucDanhComboBox = new javax.swing.JComboBox<>();
        sdtTextField = new javax.swing.JTextField();
        taiKhoanLabel = new javax.swing.JLabel();
        matKhauLabel = new javax.swing.JLabel();
        taiKhoanTextField = new javax.swing.JTextField();
        matKhauPasswordField = new javax.swing.JPasswordField();
        diaChiLabel = new javax.swing.JLabel();
        diaChiTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(700, 900));
        setSize(new java.awt.Dimension(701, 900));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setPreferredSize(new java.awt.Dimension(700, 900));

        luuButton.setBackground(new java.awt.Color(0, 255, 0));
        luuButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        luuButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/A00_Icon/Save.png"))); // NOI18N
        luuButton.setText("Lưu");
        luuButton.setToolTipText("");
        luuButton.setPreferredSize(new java.awt.Dimension(120, 40));
        luuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                luuButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(namRadioButton);
        namRadioButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        namRadioButton.setSelected(true);
        namRadioButton.setText("Nam");
        namRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namRadioButtonActionPerformed(evt);
            }
        });

        maNVTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        maNVTextField.setPreferredSize(new java.awt.Dimension(450, 40));

        buttonGroup1.add(nuRadioButton);
        nuRadioButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        nuRadioButton.setText("Nữ");

        ngaySinhLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ngaySinhLabel.setText("Ngày Sinh");
        ngaySinhLabel.setPreferredSize(new java.awt.Dimension(170, 40));

        ghiChuTextField.setColumns(20);
        ghiChuTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ghiChuTextField.setRows(5);
        ghiChuTextField.setPreferredSize(new java.awt.Dimension(450, 40));
        jScrollPane1.setViewportView(ghiChuTextField);

        sdtLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        sdtLabel.setText("Số Điện Thoại");
        sdtLabel.setPreferredSize(new java.awt.Dimension(170, 40));

        maNVLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        maNVLabel.setText("Mã Nhân Viên");
        maNVLabel.setPreferredSize(new java.awt.Dimension(170, 40));

        tenNVTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tenNVTextField.setPreferredSize(new java.awt.Dimension(450, 40));

        chucDanhLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chucDanhLabel.setText("Chức Danh");
        chucDanhLabel.setPreferredSize(new java.awt.Dimension(170, 40));

        ngaySinhTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ngaySinhTextField.setPreferredSize(new java.awt.Dimension(450, 40));

        gioiTinhLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        gioiTinhLabel.setText("Giới Tính");
        gioiTinhLabel.setPreferredSize(new java.awt.Dimension(170, 40));

        jPanelTop.setBackground(new java.awt.Color(102, 255, 0));
        jPanelTop.setPreferredSize(new java.awt.Dimension(700, 80));

        themNhanVienLabel.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        themNhanVienLabel.setForeground(new java.awt.Color(51, 51, 51));
        themNhanVienLabel.setText("Thêm Nhân Viên");

        dongButton.setBackground(new java.awt.Color(0, 255, 0));
        dongButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        dongButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/A00_Icon/Delete.png"))); // NOI18N
        dongButton.setText("Đóng");
        dongButton.setPreferredSize(new java.awt.Dimension(120, 40));
        dongButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dongButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelTopLayout = new javax.swing.GroupLayout(jPanelTop);
        jPanelTop.setLayout(jPanelTopLayout);
        jPanelTopLayout.setHorizontalGroup(
            jPanelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTopLayout.createSequentialGroup()
                .addGap(238, 238, 238)
                .addComponent(themNhanVienLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(dongButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );
        jPanelTopLayout.setVerticalGroup(
            jPanelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTopLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(jPanelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(themNhanVienLabel)
                    .addComponent(dongButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12))
        );

        cmndLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cmndLabel.setText("CMND");
        cmndLabel.setPreferredSize(new java.awt.Dimension(170, 40));

        tenNVLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tenNVLabel.setText("Tên Nhân Viên");
        tenNVLabel.setPreferredSize(new java.awt.Dimension(170, 40));

        ghiChuLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ghiChuLabel.setText("Ghi Chú");
        ghiChuLabel.setPreferredSize(new java.awt.Dimension(170, 40));

        cmndTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cmndTextField.setPreferredSize(new java.awt.Dimension(450, 40));

        chucDanhComboBox.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chucDanhComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Nhân viên" }));
        chucDanhComboBox.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        chucDanhComboBox.setPreferredSize(new java.awt.Dimension(150, 40));

        sdtTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        sdtTextField.setPreferredSize(new java.awt.Dimension(450, 40));

        taiKhoanLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        taiKhoanLabel.setText("Tài Khoản");
        taiKhoanLabel.setPreferredSize(new java.awt.Dimension(170, 40));

        matKhauLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        matKhauLabel.setText("Mật Khẩu");
        matKhauLabel.setPreferredSize(new java.awt.Dimension(170, 40));

        taiKhoanTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        taiKhoanTextField.setPreferredSize(new java.awt.Dimension(450, 40));

        matKhauPasswordField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        matKhauPasswordField.setPreferredSize(new java.awt.Dimension(450, 40));

        diaChiLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        diaChiLabel.setText("Địa Chỉ");
        diaChiLabel.setPreferredSize(new java.awt.Dimension(170, 40));

        diaChiTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        diaChiTextField.setPreferredSize(new java.awt.Dimension(450, 40));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(ghiChuLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(311, 311, 311))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(matKhauLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(matKhauPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(taiKhoanLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(taiKhoanTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sdtLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(maNVLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(maNVTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(tenNVLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(ngaySinhLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(gioiTinhLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(diaChiLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(ngaySinhTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(tenNVTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(namRadioButton)
                                            .addGap(18, 18, 18)
                                            .addComponent(nuRadioButton))
                                        .addComponent(diaChiTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(sdtTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cmndLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cmndTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(chucDanhLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(chucDanhComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(292, 292, 292)
                        .addComponent(luuButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanelTop, javax.swing.GroupLayout.PREFERRED_SIZE, 698, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanelTop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(maNVTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maNVLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tenNVLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tenNVTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ngaySinhTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(namRadioButton)
                            .addComponent(nuRadioButton)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ngaySinhLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(gioiTinhLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(diaChiLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(diaChiTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sdtLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sdtTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmndLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmndTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chucDanhLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chucDanhComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(taiKhoanLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(taiKhoanTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(matKhauLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(matKhauPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(ghiChuLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(18, 18, 18)))
                .addComponent(luuButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void namRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namRadioButtonActionPerformed

    private void luuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_luuButtonActionPerformed
        // TODO add your handling code here:
        if (maNVTextField.getText().isEmpty()||tenNVTextField.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Vui lòng điền đầy đủ Mã và Tên Nhân Viên");
        }
        else
        {
            int i=nhanVienService.getCountMANV(maNVTextField.getText());
            if (i!=0) 
            {
                JOptionPane.showMessageDialog(this, "Mã Nhân Viên đã tồn tại");
            }
            else
            {
                if(!dateValidation(ngaySinhTextField.getText()))
                {
                    JOptionPane.showMessageDialog(this, "Nhập Ngày Sinh định dạng yyyy-mm-dd");
                }
                else
                {
                    if (taiKhoanTextField.getText().isEmpty()&&String.valueOf(matKhauPasswordField.getPassword()).isEmpty())
                    {
             
                        int confirm = JOptionPane.showConfirmDialog(AddNhanVien.this, 
                                "Tài Khoản và Mật Khẩu để trống\n  Bạn có muốn tạo Tài Khoản không");
                        if (confirm==JOptionPane.YES_OPTION) 
                        {
                            JOptionPane.showMessageDialog(AddNhanVien.this, "Vui lòng điền Tài Khoản và Mật Khẩu");
                        }
                        else if (confirm==JOptionPane.NO_OPTION)
                        {
                            nhanVien.setMANV(maNVTextField.getText());
                            nhanVien.setTENNV(tenNVTextField.getText());
                            nhanVien.setNGAYSINH(ngaySinhTextField.getText());
                            String gioiTinh= "";
                            if(namRadioButton.isSelected())
                            {
                                gioiTinh = "Nam";
                            }
                            if (nuRadioButton.isSelected()) 
                            {
                                gioiTinh = "Nữ";
                            }
                            nhanVien.setGIOITINH(gioiTinh);
                            nhanVien.setDIACHI(diaChiTextField.getText());
                            nhanVien.setSDT(sdtTextField.getText());
                            nhanVien.setCMND(cmndTextField.getText());
                            String chucDanh = String.valueOf(chucDanhComboBox.getSelectedItem());
                            nhanVien.setCHUCDANH(chucDanh);
                            nhanVien.setTAIKHOAN(taiKhoanTextField.getText());
                            nhanVien.setMATKHAU(String.valueOf(matKhauPasswordField.getPassword()));
                            nhanVien.setGHICHU(ghiChuTextField.getText());
                            nhanVienService.addNhanVien(nhanVien);
                            JOptionPane.showMessageDialog(this, "Lưu thành công!");
                        }
                            
                    }
                    else if (taiKhoanTextField.getText().isEmpty() || String.valueOf(matKhauPasswordField.getPassword()).isEmpty())
                    {
                        JOptionPane.showMessageDialog(AddNhanVien.this, "Vui lòng điền đủ Tài Khoản và Mật Khẩu nếu muốn tạo Tài Khoản");
                    }
                    else
                    {
                    int j=nhanVienService.getCountTAIKHOAN(taiKhoanTextField.getText());
                    if(j!=0)
                    {
                        JOptionPane.showMessageDialog(this, "Tài Khoản đã tồn tại");
                    }
                    else
                    {
                        nhanVien.setMANV(maNVTextField.getText());
                        nhanVien.setTENNV(tenNVTextField.getText());
                        nhanVien.setNGAYSINH(ngaySinhTextField.getText());
                        String gioiTinh= "";
                        if(namRadioButton.isSelected())
                        {
                            gioiTinh = "Nam";
                        }
                        if (nuRadioButton.isSelected()) 
                        {
                            gioiTinh = "Nữ";
                        }
                        nhanVien.setGIOITINH(gioiTinh);
                        nhanVien.setDIACHI(diaChiTextField.getText());
                        nhanVien.setSDT(sdtTextField.getText());
                        nhanVien.setCMND(cmndTextField.getText());
                        String chucDanh = String.valueOf(chucDanhComboBox.getSelectedItem());
                        nhanVien.setCHUCDANH(chucDanh);
                        nhanVien.setTAIKHOAN(taiKhoanTextField.getText());
                        nhanVien.setMATKHAU(String.valueOf(matKhauPasswordField.getPassword()));
                        nhanVien.setGHICHU(ghiChuTextField.getText());
                        nhanVienService.addNhanVien(nhanVien);
                        JOptionPane.showMessageDialog(this, "Lưu thành công!");
                    }           
                }
            }}
        }      

    }//GEN-LAST:event_luuButtonActionPerformed

    private void dongButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dongButtonActionPerformed
        // TODO add your handling code here:
        
        this.dispose();
    }//GEN-LAST:event_dongButtonActionPerformed
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddNhanVien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> chucDanhComboBox;
    private javax.swing.JLabel chucDanhLabel;
    private javax.swing.JLabel cmndLabel;
    private javax.swing.JTextField cmndTextField;
    private javax.swing.JLabel diaChiLabel;
    private javax.swing.JTextField diaChiTextField;
    private javax.swing.JButton dongButton;
    private javax.swing.JLabel ghiChuLabel;
    private javax.swing.JTextArea ghiChuTextField;
    private javax.swing.JLabel gioiTinhLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelTop;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton luuButton;
    private javax.swing.JLabel maNVLabel;
    private javax.swing.JTextField maNVTextField;
    private javax.swing.JLabel matKhauLabel;
    private javax.swing.JPasswordField matKhauPasswordField;
    private javax.swing.JRadioButton namRadioButton;
    private javax.swing.JLabel ngaySinhLabel;
    private javax.swing.JTextField ngaySinhTextField;
    private javax.swing.JRadioButton nuRadioButton;
    private javax.swing.JLabel sdtLabel;
    private javax.swing.JTextField sdtTextField;
    private javax.swing.JLabel taiKhoanLabel;
    private javax.swing.JTextField taiKhoanTextField;
    private javax.swing.JLabel tenNVLabel;
    private javax.swing.JTextField tenNVTextField;
    private javax.swing.JLabel themNhanVienLabel;
    // End of variables declaration//GEN-END:variables
}
