/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package A04_NhanVien;

import static A00_Support.DateValidation.dateValidation;
import javax.swing.JOptionPane;

/**
 *
 * @author ADMIN
 */
public class EditNhanVien extends javax.swing.JFrame {
    private NhanVien nhanVien;
    NhanVienService nhanVienService;
    String MANVdangsua;
    String TAIKHOANdangsua;
    /**
     * Creates new form EditNhanVienFrame
     */
    public EditNhanVien(String MANV) {
        nhanVien = new NhanVien();
        nhanVienService = new NhanVienService();
        nhanVien = nhanVienService.getNhanVienByMANV(MANV);
        initComponents();
        MANVdangsua=nhanVien.getMANV();
        TAIKHOANdangsua=nhanVien.getTAIKHOAN();
        maNVTextField.setText(nhanVien.getMANV());
        tenNVTextField.setText(nhanVien.getTENNV());
        ngaySinhTextField.setText(nhanVien.getNGAYSINH());
        String gioiTinh = String.valueOf(nhanVien.getGIOITINH());
        String nam="Nam";
        if (nam.equals(gioiTinh)) {
            namRadioButton.setSelected(true);
        }else{
            nuRadioButton.setSelected(true);
        }
        diaChiTextField.setText(nhanVien.getDIACHI());
        sdtTextField.setText(nhanVien.getSDT());
        cmndTextField.setText(nhanVien.getCMND());
        String chucDanh = String.valueOf(nhanVien.getCHUCDANH());
        String admin="Admin";
        if (admin.equals(chucDanh))
        {
            chucDanhComboBox.setSelectedIndex(0);
        }
        else
        {
            chucDanhComboBox.setSelectedIndex(1);
        }
        taiKhoanTextField.setText(nhanVien.getTAIKHOAN());
        matKhauPasswordField.setText(nhanVien.getMATKHAU());       
        ghiChuTextField.setText(nhanVien.getGHICHU());       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        tenNVLabel = new javax.swing.JLabel();
        matKhauLabel = new javax.swing.JLabel();
        ngaySinhLabel = new javax.swing.JLabel();
        taiKhoanTextField = new javax.swing.JTextField();
        gioiTinhLabel = new javax.swing.JLabel();
        matKhauPasswordField = new javax.swing.JPasswordField();
        cmndLabel = new javax.swing.JLabel();
        sdtLabel = new javax.swing.JLabel();
        ghiChuLabel = new javax.swing.JLabel();
        chucDanhLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ghiChuTextField = new javax.swing.JTextArea();
        namRadioButton = new javax.swing.JRadioButton();
        nuRadioButton = new javax.swing.JRadioButton();
        maNVTextField = new javax.swing.JTextField();
        luuButton = new javax.swing.JButton();
        tenNVTextField = new javax.swing.JTextField();
        maNVLabel = new javax.swing.JLabel();
        ngaySinhTextField = new javax.swing.JTextField();
        cmndTextField = new javax.swing.JTextField();
        sdtTextField = new javax.swing.JTextField();
        chucDanhComboBox = new javax.swing.JComboBox<>();
        taiKhoanLabel = new javax.swing.JLabel();
        jPanelTop = new javax.swing.JPanel();
        chinhSuaNhanVienLabel = new javax.swing.JLabel();
        dongButton = new javax.swing.JButton();
        diaChiLabel = new javax.swing.JLabel();
        diaChiTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(700, 900));
        setSize(new java.awt.Dimension(700, 900));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tenNVLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tenNVLabel.setText("Tên Nhân Viên");
        tenNVLabel.setPreferredSize(new java.awt.Dimension(170, 40));

        matKhauLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        matKhauLabel.setText("Mật Khẩu");
        matKhauLabel.setPreferredSize(new java.awt.Dimension(170, 40));

        ngaySinhLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ngaySinhLabel.setText("Ngày Sinh");
        ngaySinhLabel.setPreferredSize(new java.awt.Dimension(170, 40));

        taiKhoanTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        taiKhoanTextField.setPreferredSize(new java.awt.Dimension(450, 40));

        gioiTinhLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        gioiTinhLabel.setText("Giới Tính");
        gioiTinhLabel.setPreferredSize(new java.awt.Dimension(170, 40));

        matKhauPasswordField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        matKhauPasswordField.setMinimumSize(new java.awt.Dimension(450, 40));
        matKhauPasswordField.setPreferredSize(new java.awt.Dimension(450, 40));

        cmndLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cmndLabel.setText("CMND");
        cmndLabel.setPreferredSize(new java.awt.Dimension(170, 40));

        sdtLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        sdtLabel.setText("Số Điện Thoại");
        sdtLabel.setPreferredSize(new java.awt.Dimension(170, 40));

        ghiChuLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ghiChuLabel.setText("Ghi Chú");

        chucDanhLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chucDanhLabel.setText("Chức Danh");
        chucDanhLabel.setPreferredSize(new java.awt.Dimension(170, 40));

        ghiChuTextField.setColumns(20);
        ghiChuTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ghiChuTextField.setRows(5);
        jScrollPane1.setViewportView(ghiChuTextField);

        buttonGroup1.add(namRadioButton);
        namRadioButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        namRadioButton.setSelected(true);
        namRadioButton.setText("Nam");
        namRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(nuRadioButton);
        nuRadioButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        nuRadioButton.setText("Nữ");

        maNVTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        maNVTextField.setPreferredSize(new java.awt.Dimension(450, 40));

        luuButton.setBackground(new java.awt.Color(0, 255, 0));
        luuButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        luuButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/A00_Icon/Save.png"))); // NOI18N
        luuButton.setText("Lưu");
        luuButton.setToolTipText("");
        luuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                luuButtonActionPerformed(evt);
            }
        });

        tenNVTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tenNVTextField.setPreferredSize(new java.awt.Dimension(450, 40));

        maNVLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        maNVLabel.setText("Mã Nhân Viên");
        maNVLabel.setPreferredSize(new java.awt.Dimension(170, 40));

        ngaySinhTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ngaySinhTextField.setPreferredSize(new java.awt.Dimension(450, 40));

        cmndTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cmndTextField.setPreferredSize(new java.awt.Dimension(450, 40));

        sdtTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        sdtTextField.setPreferredSize(new java.awt.Dimension(450, 40));

        chucDanhComboBox.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chucDanhComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Nhân viên" }));
        chucDanhComboBox.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        chucDanhComboBox.setPreferredSize(new java.awt.Dimension(150, 40));

        taiKhoanLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        taiKhoanLabel.setText("Tài Khoản");
        taiKhoanLabel.setPreferredSize(new java.awt.Dimension(170, 40));

        jPanelTop.setBackground(new java.awt.Color(102, 255, 0));

        chinhSuaNhanVienLabel.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        chinhSuaNhanVienLabel.setForeground(new java.awt.Color(51, 51, 51));
        chinhSuaNhanVienLabel.setText("Chỉnh Sửa Thông Tin Nhân Viên");

        dongButton.setBackground(new java.awt.Color(0, 255, 0));
        dongButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        dongButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/A00_Icon/Delete.png"))); // NOI18N
        dongButton.setText("Đóng");
        dongButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dongButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelTopLayout = new javax.swing.GroupLayout(jPanelTop);
        jPanelTop.setLayout(jPanelTopLayout);
        jPanelTopLayout.setHorizontalGroup(
            jPanelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTopLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(chinhSuaNhanVienLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dongButton)
                .addContainerGap())
        );
        jPanelTopLayout.setVerticalGroup(
            jPanelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTopLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dongButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(chinhSuaNhanVienLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(14, 14, 14))
        );

        diaChiLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        diaChiLabel.setText("Địa Chỉ");
        diaChiLabel.setPreferredSize(new java.awt.Dimension(170, 40));

        diaChiTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        diaChiTextField.setPreferredSize(new java.awt.Dimension(450, 40));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelTop, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(cmndLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cmndTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(chucDanhLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(chucDanhComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(taiKhoanLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(taiKhoanTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(diaChiLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(diaChiTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(gioiTinhLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(namRadioButton)
                                .addGap(72, 72, 72)
                                .addComponent(nuRadioButton))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(ngaySinhLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ngaySinhTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tenNVLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(maNVLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(19, 19, 19)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(maNVTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tenNVTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(sdtLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(sdtTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(matKhauLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ghiChuLabel))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(matKhauPasswordField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jScrollPane1)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(294, 294, 294)
                        .addComponent(luuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanelTop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(maNVLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maNVTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tenNVLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tenNVTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ngaySinhLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ngaySinhTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gioiTinhLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(namRadioButton)
                    .addComponent(nuRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(diaChiLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(diaChiTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sdtLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sdtTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmndLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmndTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chucDanhLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chucDanhComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(taiKhoanLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(taiKhoanTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(matKhauLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(matKhauPasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ghiChuLabel)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(luuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void namRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namRadioButtonActionPerformed

    private void luuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_luuButtonActionPerformed
        // TODO add your handling code here:
        if (maNVTextField.getText().isEmpty()||tenNVTextField.getText().isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Vui lòng điền đầy đủ Mã và Tên Nhân Viên");
        }
        else
        {
            int i=nhanVienService.getCountMANV(maNVTextField.getText());
            if (i!=0 && !MANVdangsua.equals(maNVTextField.getText())) 
            {
                JOptionPane.showMessageDialog(this, "Mã Nhân Viên bị trùng lặp");
                maNVTextField.setText(MANVdangsua);
            }
            else
            {
                if(!dateValidation(ngaySinhTextField.getText()))
                {
                    JOptionPane.showMessageDialog(this, "Nhập Ngày Sinh định dạng yyyy-mm-dd");
                }
                else
                {
                    if (taiKhoanTextField.getText().isEmpty()&&String.valueOf(matKhauPasswordField.getPassword()).isEmpty())
                    {
                        int confirm = JOptionPane.showConfirmDialog(EditNhanVien.this, 
                            "Tài Khoản và Mật Khẩu để trống\n  Bạn có muốn nhập Tài Khoản và Mật Khẩu không","Thông Báo",1);
                        if (confirm==JOptionPane.YES_OPTION) 
                        {
                            JOptionPane.showMessageDialog(EditNhanVien.this, "Vui lòng điền Tài Khoản và Mật Khẩu");
                        }
                        else if (confirm==JOptionPane.NO_OPTION)
                        {
                            nhanVien.setMANV(maNVTextField.getText());
                            nhanVien.setTENNV(tenNVTextField.getText());
                            nhanVien.setNGAYSINH(ngaySinhTextField.getText());
                            String gioiTinh = "";
                            if(namRadioButton.isSelected()){
                                gioiTinh = "Nam";
                            }
                            if (nuRadioButton.isSelected()) {
                                gioiTinh = "Nữ";
                            }
                            nhanVien.setGIOITINH(gioiTinh);
                            nhanVien.setDIACHI(diaChiTextField.getText());
                            nhanVien.setSDT(sdtTextField.getText());
                            nhanVien.setCMND(cmndTextField.getText());
                            String chucDanh = String.valueOf(chucDanhComboBox.getSelectedItem());
                            nhanVien.setCHUCDANH(chucDanh);
                            nhanVien.setTAIKHOAN(taiKhoanTextField.getText());
                            nhanVien.setMATKHAU(String.valueOf(matKhauPasswordField.getPassword()));        
                            nhanVien.setGHICHU(ghiChuTextField.getText());
                            nhanVienService.updateNhanVien(nhanVien);
                            JOptionPane.showMessageDialog(this, "Lưu thành công!");
                        }
                    }
                    else if (taiKhoanTextField.getText().isEmpty() || String.valueOf(matKhauPasswordField.getPassword()).isEmpty())
                    {
                        JOptionPane.showMessageDialog(EditNhanVien.this, "Vui lòng điền đủ Tài Khoản và Mật Khẩu nếu muốn tạo Tài Khoản");
                    }
                    else 
                    {
                        int j=nhanVienService.getCountTAIKHOAN(taiKhoanTextField.getText());
                        if(j!=0 && !nhanVienService.getNhanVienByMANV(MANVdangsua).getTAIKHOAN().equals(taiKhoanTextField.getText()))
                        {
                            JOptionPane.showMessageDialog(this, "Tài Khoản bị trùng lặp");
                            taiKhoanTextField.setText(TAIKHOANdangsua);
                        }
                        else
                        {
                            nhanVien.setMANV(maNVTextField.getText());
                            nhanVien.setTENNV(tenNVTextField.getText());
                            nhanVien.setNGAYSINH(ngaySinhTextField.getText());
                            String gioiTinh = "";
                            if(namRadioButton.isSelected()){
                                gioiTinh = "Nam";
                            }
                            if (nuRadioButton.isSelected()) {
                                gioiTinh = "Nữ";
                            }
                            nhanVien.setGIOITINH(gioiTinh);
                            nhanVien.setDIACHI(diaChiTextField.getText());
                            nhanVien.setSDT(sdtTextField.getText());
                            nhanVien.setCMND(cmndTextField.getText());
                            String chucDanh = String.valueOf(chucDanhComboBox.getSelectedItem());
                            nhanVien.setCHUCDANH(chucDanh);
                            nhanVien.setTAIKHOAN(taiKhoanTextField.getText());
                            nhanVien.setMATKHAU(String.valueOf(matKhauPasswordField.getPassword()));        
                            nhanVien.setGHICHU(ghiChuTextField.getText());
                            nhanVienService.updateNhanVien(nhanVien);
                            JOptionPane.showMessageDialog(this, "Lưu thành công!");
                        }
                    }
                }
            }   
        }    
    }//GEN-LAST:event_luuButtonActionPerformed

    private void dongButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dongButtonActionPerformed
        // TODO add your handling code here:
        
        this.dispose();
    }//GEN-LAST:event_dongButtonActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel chinhSuaNhanVienLabel;
    private javax.swing.JComboBox<String> chucDanhComboBox;
    private javax.swing.JLabel chucDanhLabel;
    private javax.swing.JLabel cmndLabel;
    private javax.swing.JTextField cmndTextField;
    private javax.swing.JLabel diaChiLabel;
    private javax.swing.JTextField diaChiTextField;
    private javax.swing.JButton dongButton;
    private javax.swing.JLabel ghiChuLabel;
    private javax.swing.JTextArea ghiChuTextField;
    private javax.swing.JLabel gioiTinhLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelTop;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton luuButton;
    private javax.swing.JLabel maNVLabel;
    private javax.swing.JTextField maNVTextField;
    private javax.swing.JLabel matKhauLabel;
    private javax.swing.JPasswordField matKhauPasswordField;
    private javax.swing.JRadioButton namRadioButton;
    private javax.swing.JLabel ngaySinhLabel;
    private javax.swing.JTextField ngaySinhTextField;
    private javax.swing.JRadioButton nuRadioButton;
    private javax.swing.JLabel sdtLabel;
    private javax.swing.JTextField sdtTextField;
    private javax.swing.JLabel taiKhoanLabel;
    private javax.swing.JTextField taiKhoanTextField;
    private javax.swing.JLabel tenNVLabel;
    private javax.swing.JTextField tenNVTextField;
    // End of variables declaration//GEN-END:variables
}
