/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package A04_NhanVien;

import A02_BanHang.FormBanHang;
import A01_DangNhap.FormDangNhap;
import A11_BaoCao.FormBaoCao;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import A00_Connection.JDBCConnection;
import A03_SanPham.FormSanPham;
import A07_HoaDon.FormHoaDon;
import A05_KhachHang.FormKhachHang;
import A06_NhaCungCap.FormNhaCungCap;
import A09_DonNhapHang.FormDonNhapHang;
import java.awt.Font;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author ADMIN
 */
public class FormNhanVien extends javax.swing.JFrame {
    NhanVienService nhanVienService;
    DefaultTableModel defaultTableModel;

    /**
     * Creates new form FromNhanVien
     */
    public FormNhanVien() {
        initComponents();
        nhanVienService = new NhanVienService();
        defaultTableModel = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; //To change body of generated methods, choose Tools | Templates.
            }
            
        };
        
        nhanVienTable.setModel(defaultTableModel);
        
        defaultTableModel.addColumn("Mã Nhân Viên");
        defaultTableModel.addColumn("Tên Nhân Viên");
        defaultTableModel.addColumn("Ngày Sinh");
        defaultTableModel.addColumn("Giới Tính");
        defaultTableModel.addColumn("Địa Chỉ");
        defaultTableModel.addColumn("SĐT");
        defaultTableModel.addColumn("CMND");
        defaultTableModel.addColumn("Chức Danh");
        defaultTableModel.addColumn("Tài Khoản");
        defaultTableModel.addColumn("Mật Khẩu");
        defaultTableModel.addColumn("Ghi Chú");
        nhanVienTable.setRowHeight(24);
        nhanVienTable.setFont(new Font("Segoe UI",Font.PLAIN,18));
        nhanVienTable.getTableHeader().setFont(new Font("Segoe",Font.BOLD,18));
        nhanVienTable.getColumnModel().getColumn(0).setPreferredWidth(100);
        nhanVienTable.getColumnModel().getColumn(1).setPreferredWidth(100);
        setTableData(nhanVienService.getAllNhanviens());
    }
    private void setTableData(List<NhanVien> nhanViens){
        for(NhanVien nhanVien : nhanViens){
            defaultTableModel.addRow(new Object[]{nhanVien.getMANV(), nhanVien.getTENNV(),nhanVien.getNGAYSINH(), nhanVien.getGIOITINH(),
            nhanVien.getDIACHI(), nhanVien.getSDT(), nhanVien.getCMND(), nhanVien.getCHUCDANH(),nhanVien.getTAIKHOAN(), nhanVien.getMATKHAU(),nhanVien.getGHICHU()});
                   
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        sanPhamButton = new javax.swing.JButton();
        hoaDonButton = new javax.swing.JButton();
        nhapHangButton = new javax.swing.JButton();
        nhaCungCapButton = new javax.swing.JButton();
        baoCaoButton = new javax.swing.JButton();
        khachHangButton = new javax.swing.JButton();
        dangXuatButton = new javax.swing.JButton();
        nhanVienButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        nhanVienTable = new javax.swing.JTable();
        timKiemLabel = new javax.swing.JLabel();
        suaButton = new javax.swing.JButton();
        xoaButton = new javax.swing.JButton();
        refreshButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        adminCheckBox = new javax.swing.JCheckBox();
        nhanVienCheckBox = new javax.swing.JCheckBox();
        tatCaCheckBox = new javax.swing.JCheckBox();
        themButton = new javax.swing.JButton();
        timKiemTextField = new javax.swing.JTextField();
        nhanVienLabel = new javax.swing.JLabel();
        chucDanhLabel = new javax.swing.JLabel();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jCheckBoxMenuItem2.setSelected(true);
        jCheckBoxMenuItem2.setText("jCheckBoxMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setSize(new java.awt.Dimension(1508, 668));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setPreferredSize(new java.awt.Dimension(1508, 668));

        jPanel8.setBackground(new java.awt.Color(102, 255, 0));
        jPanel8.setPreferredSize(new java.awt.Dimension(1507, 80));

        sanPhamButton.setBackground(new java.awt.Color(102, 255, 102));
        sanPhamButton.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        sanPhamButton.setForeground(new java.awt.Color(51, 51, 51));
        sanPhamButton.setText("Sản Phẩm");
        sanPhamButton.setPreferredSize(new java.awt.Dimension(170, 50));
        sanPhamButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sanPhamButtonActionPerformed(evt);
            }
        });

        hoaDonButton.setBackground(new java.awt.Color(102, 255, 102));
        hoaDonButton.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        hoaDonButton.setForeground(new java.awt.Color(51, 51, 51));
        hoaDonButton.setText("Hóa Đơn");
        hoaDonButton.setPreferredSize(new java.awt.Dimension(170, 50));
        hoaDonButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hoaDonButtonActionPerformed(evt);
            }
        });

        nhapHangButton.setBackground(new java.awt.Color(102, 255, 102));
        nhapHangButton.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        nhapHangButton.setForeground(new java.awt.Color(51, 51, 51));
        nhapHangButton.setText("Nhập Hàng");
        nhapHangButton.setPreferredSize(new java.awt.Dimension(170, 50));
        nhapHangButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nhapHangButtonActionPerformed(evt);
            }
        });

        nhaCungCapButton.setBackground(new java.awt.Color(102, 255, 102));
        nhaCungCapButton.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        nhaCungCapButton.setForeground(new java.awt.Color(51, 51, 51));
        nhaCungCapButton.setText("Nhà Cung Cấp");
        nhaCungCapButton.setPreferredSize(new java.awt.Dimension(170, 50));
        nhaCungCapButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nhaCungCapButtonActionPerformed(evt);
            }
        });

        baoCaoButton.setBackground(new java.awt.Color(102, 255, 102));
        baoCaoButton.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        baoCaoButton.setForeground(new java.awt.Color(51, 51, 51));
        baoCaoButton.setText("Báo Cáo");
        baoCaoButton.setPreferredSize(new java.awt.Dimension(170, 50));
        baoCaoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baoCaoButtonActionPerformed(evt);
            }
        });

        khachHangButton.setBackground(new java.awt.Color(102, 255, 102));
        khachHangButton.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        khachHangButton.setForeground(new java.awt.Color(51, 51, 51));
        khachHangButton.setText("Khách Hàng");
        khachHangButton.setPreferredSize(new java.awt.Dimension(170, 50));
        khachHangButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                khachHangButtonActionPerformed(evt);
            }
        });

        dangXuatButton.setBackground(new java.awt.Color(102, 255, 102));
        dangXuatButton.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        dangXuatButton.setForeground(new java.awt.Color(51, 51, 51));
        dangXuatButton.setText("Đăng Xuất");
        dangXuatButton.setPreferredSize(new java.awt.Dimension(170, 50));
        dangXuatButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dangXuatButtonActionPerformed(evt);
            }
        });

        nhanVienButton.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        nhanVienButton.setText("Nhân Viên");
        nhanVienButton.setPreferredSize(new java.awt.Dimension(170, 50));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sanPhamButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(nhanVienButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(khachHangButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(hoaDonButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(nhaCungCapButton, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(nhapHangButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(baoCaoButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(dangXuatButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nhanVienButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sanPhamButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hoaDonButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nhapHangButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(khachHangButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nhaCungCapButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(baoCaoButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dangXuatButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        nhanVienTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        nhanVienTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(nhanVienTable);

        timKiemLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        timKiemLabel.setText("Tìm kiếm ");
        timKiemLabel.setPreferredSize(new java.awt.Dimension(80, 40));

        suaButton.setBackground(new java.awt.Color(0, 255, 0));
        suaButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        suaButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/A00_Icon/Edit.png"))); // NOI18N
        suaButton.setText("Sửa");
        suaButton.setPreferredSize(new java.awt.Dimension(120, 40));
        suaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suaButtonActionPerformed(evt);
            }
        });

        xoaButton.setBackground(new java.awt.Color(0, 255, 0));
        xoaButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        xoaButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/A00_Icon/icons8-delete-bin-32.png"))); // NOI18N
        xoaButton.setText("Xóa");
        xoaButton.setPreferredSize(new java.awt.Dimension(120, 40));
        xoaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xoaButtonActionPerformed(evt);
            }
        });

        refreshButton.setBackground(new java.awt.Color(0, 255, 0));
        refreshButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        refreshButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/A00_Icon/Refresh.png"))); // NOI18N
        refreshButton.setText("Refresh");
        refreshButton.setPreferredSize(new java.awt.Dimension(120, 40));
        refreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshButtonActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        buttonGroup1.add(adminCheckBox);
        adminCheckBox.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        adminCheckBox.setSelected(true);
        adminCheckBox.setText("Admin");
        adminCheckBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adminCheckBoxMouseClicked(evt);
            }
        });
        adminCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminCheckBoxActionPerformed(evt);
            }
        });

        buttonGroup1.add(nhanVienCheckBox);
        nhanVienCheckBox.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        nhanVienCheckBox.setText("Nhân Viên");
        nhanVienCheckBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nhanVienCheckBoxMouseClicked(evt);
            }
        });
        nhanVienCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nhanVienCheckBoxActionPerformed(evt);
            }
        });

        buttonGroup1.add(tatCaCheckBox);
        tatCaCheckBox.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tatCaCheckBox.setText("Tất Cả");
        tatCaCheckBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tatCaCheckBoxMouseClicked(evt);
            }
        });
        tatCaCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tatCaCheckBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nhanVienCheckBox)
                    .addComponent(adminCheckBox)
                    .addComponent(tatCaCheckBox))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(adminCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nhanVienCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tatCaCheckBox)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        themButton.setBackground(new java.awt.Color(0, 255, 0));
        themButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        themButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/A00_Icon/Add.png"))); // NOI18N
        themButton.setText("Thêm");
        themButton.setPreferredSize(new java.awt.Dimension(120, 40));
        themButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themButtonActionPerformed(evt);
            }
        });

        timKiemTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        timKiemTextField.setPreferredSize(new java.awt.Dimension(350, 40));
        timKiemTextField.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                timKiemTextFieldCaretUpdate(evt);
            }
        });

        nhanVienLabel.setBackground(new java.awt.Color(60, 63, 100));
        nhanVienLabel.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        nhanVienLabel.setForeground(new java.awt.Color(51, 51, 51));
        nhanVienLabel.setText("Nhân Viên");

        chucDanhLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        chucDanhLabel.setText("Chức danh");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nhanVienLabel)
                    .addComponent(chucDanhLabel))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(timKiemLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(timKiemTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(themButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(xoaButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(suaButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(refreshButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 1295, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(chucDanhLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nhanVienLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(themButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(xoaButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(timKiemLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(timKiemTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(refreshButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(suaButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, 1506, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tatCaCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tatCaCheckBoxActionPerformed
        // TODO add your handling code here:
        try {           
            Connection Con = JDBCConnection.getJDBCConnection();
            PreparedStatement Pst = Con.prepareStatement("select * from nhanvien");
            ResultSet Rs = Pst.executeQuery();
            defaultTableModel = (DefaultTableModel)nhanVienTable.getModel();
            defaultTableModel.setRowCount(0);
            while (Rs.next()) {
                Object objList[] = {Rs.getString("MANV"), Rs.getString("TENNV"), Rs.getDate("NGAYSINH"), Rs.getString("GIOITINH"), Rs.getString("DIACHI"),Rs.getString("SDT"),Rs.getString("CMND"),Rs.getString("CHUCDANH"),Rs.getString("TAIKHOAN"),Rs.getString("MATKHAU"),Rs.getString("GHICHU")};
                defaultTableModel.addRow(objList);                
            }
        } catch (SQLException ex) {
            Logger.getLogger(FormBanHang.class.getName()).log(Level.SEVERE,null,ex);
        }
    }//GEN-LAST:event_tatCaCheckBoxActionPerformed

    private void themButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_themButtonActionPerformed
        // TODO add your handling code here:
        new AddNhanVien().setVisible(true);
        
    }//GEN-LAST:event_themButtonActionPerformed

    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed
        // TODO add your handling code here:
        defaultTableModel.setRowCount(0);
        setTableData(nhanVienService.getAllNhanviens());
    }//GEN-LAST:event_refreshButtonActionPerformed

    private void xoaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xoaButtonActionPerformed
        // TODO add your handling code here:
        int row = nhanVienTable.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(FormNhanVien.this, "Vui lòng chọn Nhân Viên cần xóa","Lỗi", JOptionPane.ERROR_MESSAGE);
        }else{
            int confirm = JOptionPane.showConfirmDialog(FormNhanVien.this, "Bạn chắc chắn muốn xóa không?");
            
            if (confirm == JOptionPane.YES_OPTION) {
                String MANV = String.valueOf( nhanVienTable.getValueAt(row, 0));
                
                nhanVienService.deleteNhanVien(MANV);
                
                defaultTableModel.setRowCount(0);
                setTableData(nhanVienService.getAllNhanviens());
            }
        }
    }//GEN-LAST:event_xoaButtonActionPerformed

    private void suaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suaButtonActionPerformed
        // TODO add your handling code here:
        int row = nhanVienTable.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(FormNhanVien.this, "Vui lòng chọn Nhân Viên cần sửa","Lỗi", JOptionPane.ERROR_MESSAGE);
        }else{                      
            String MANV = String.valueOf( nhanVienTable.getValueAt(row, 0));
                
            new EditNhanVien(MANV).setVisible(true);
            
        }
    }//GEN-LAST:event_suaButtonActionPerformed

    private void timKiemTextFieldCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_timKiemTextFieldCaretUpdate
        // TODO add your handling code here:
        if (tatCaCheckBox.isSelected())
        {
        try {           
            Connection Con = JDBCConnection.getJDBCConnection();
            PreparedStatement Pst = Con.prepareStatement("select * from nhanvien where TENNV like N'%"+timKiemTextField.getText()+"%' or MANV like N'%"+timKiemTextField.getText()+"%'");
            ResultSet Rs = Pst.executeQuery();
            defaultTableModel = (DefaultTableModel)nhanVienTable.getModel();
            defaultTableModel.setRowCount(0);
            while (Rs.next()) {
                Object objList[] = {Rs.getString("MANV"), Rs.getString("TENNV"), Rs.getDate("NGAYSINH"), Rs.getString("GIOITINH"), Rs.getString("DIACHI"),Rs.getString("SDT"),Rs.getString("CMND"),Rs.getString("CHUCDANH"),Rs.getString("TAIKHOAN"),Rs.getString("MATKHAU"),Rs.getString("GHICHU")};
                defaultTableModel.addRow(objList);                
            }
        } catch (SQLException ex) {
            Logger.getLogger(FormBanHang.class.getName()).log(Level.SEVERE,null,ex);
        }
        }
        else if (adminCheckBox.isSelected()){
            try {           
            Connection Con = JDBCConnection.getJDBCConnection();
            PreparedStatement Pst = Con.prepareStatement("select * from nhanvien where (TENNV like N'%"+timKiemTextField.getText()+"%' or MANV like N'%"+timKiemTextField.getText()+"%') and CHUCDANH like 'Admin'");
            ResultSet Rs = Pst.executeQuery();
            defaultTableModel = (DefaultTableModel)nhanVienTable.getModel();
            defaultTableModel.setRowCount(0);
            while (Rs.next()) {
                Object objList[] = {Rs.getString("MANV"), Rs.getString("TENNV"), Rs.getDate("NGAYSINH"), Rs.getString("GIOITINH"), Rs.getString("DIACHI"),Rs.getString("SDT"),Rs.getString("CMND"),Rs.getString("CHUCDANH"),Rs.getString("TAIKHOAN"),Rs.getString("MATKHAU"),Rs.getString("GHICHU")};
                defaultTableModel.addRow(objList);                
            }
        } catch (SQLException ex) {
            Logger.getLogger(FormBanHang.class.getName()).log(Level.SEVERE,null,ex);
        }
            
        }
        else if (nhanVienCheckBox.isSelected()){
             try {           
            Connection Con = JDBCConnection.getJDBCConnection();
            PreparedStatement Pst = Con.prepareStatement("select * from nhanvien where (TENNV like N'%"+timKiemTextField.getText()+"%' or MANV like N'%"+timKiemTextField.getText()+"%') and CHUCDANH like N'Nhân viên'");
            ResultSet Rs = Pst.executeQuery();
            defaultTableModel = (DefaultTableModel)nhanVienTable.getModel();
            defaultTableModel.setRowCount(0);
            while (Rs.next()) {
                Object objList[] = {Rs.getString("MANV"), Rs.getString("TENNV"), Rs.getDate("NGAYSINH"), Rs.getString("GIOITINH"), Rs.getString("DIACHI"),Rs.getString("SDT"),Rs.getString("CMND"),Rs.getString("CHUCDANH"),Rs.getString("TAIKHOAN"),Rs.getString("MATKHAU"),Rs.getString("GHICHU")};
                defaultTableModel.addRow(objList);                
            }
        } catch (SQLException ex) {
            Logger.getLogger(FormBanHang.class.getName()).log(Level.SEVERE,null,ex);
        }
        }
    }//GEN-LAST:event_timKiemTextFieldCaretUpdate

    private void adminCheckBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminCheckBoxMouseClicked
        // TODO add your handling code here:
        try {           
            Connection Con = JDBCConnection.getJDBCConnection();
            PreparedStatement Pst = Con.prepareStatement("select * from nhanvien where CHUCDANH like N'%Admin%'");
            ResultSet Rs = Pst.executeQuery();
            defaultTableModel = (DefaultTableModel)nhanVienTable.getModel();
            defaultTableModel.setRowCount(0);
            while (Rs.next()) {
                Object objList[] = {Rs.getString("MANV"), Rs.getString("TENNV"), Rs.getDate("NGAYSINH"), Rs.getString("GIOITINH"), Rs.getString("DIACHI"),Rs.getString("SDT"),Rs.getString("CMND"),Rs.getString("CHUCDANH"),Rs.getString("TAIKHOAN"),Rs.getString("MATKHAU"),Rs.getString("GHICHU")};
                defaultTableModel.addRow(objList);                
            }
        } catch (SQLException ex) {
            Logger.getLogger(FormBanHang.class.getName()).log(Level.SEVERE,null,ex);
        }
    }//GEN-LAST:event_adminCheckBoxMouseClicked

    private void nhanVienCheckBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nhanVienCheckBoxMouseClicked
        // TODO add your handling code here:
        try {           
            Connection Con = JDBCConnection.getJDBCConnection();
            PreparedStatement Pst = Con.prepareStatement("select * from nhanvien where CHUCDANH like N'%Nhân viên%'");
            ResultSet Rs = Pst.executeQuery();
            defaultTableModel = (DefaultTableModel)nhanVienTable.getModel();
            defaultTableModel.setRowCount(0);
            while (Rs.next()) {
                Object objList[] = {Rs.getString("MANV"), Rs.getString("TENNV"), Rs.getDate("NGAYSINH"), Rs.getString("GIOITINH"), Rs.getString("DIACHI"),Rs.getString("SDT"),Rs.getString("CMND"),Rs.getString("CHUCDANH"),Rs.getString("TAIKHOAN"),Rs.getString("MATKHAU"),Rs.getString("GHICHU")};
                defaultTableModel.addRow(objList);                
            }
        } catch (SQLException ex) {
            Logger.getLogger(FormBanHang.class.getName()).log(Level.SEVERE,null,ex);
        }
    }//GEN-LAST:event_nhanVienCheckBoxMouseClicked

    private void tatCaCheckBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tatCaCheckBoxMouseClicked
        // TODO add your handling code here:
        try {           
            Connection Con = JDBCConnection.getJDBCConnection();
            PreparedStatement Pst = Con.prepareStatement("select * from nhanvien");
            ResultSet Rs = Pst.executeQuery();
            defaultTableModel = (DefaultTableModel)nhanVienTable.getModel();
            defaultTableModel.setRowCount(0);
            while (Rs.next()) {
                Object objList[] = {Rs.getString("MANV"), Rs.getString("TENNV"), Rs.getDate("NGAYSINH"), Rs.getString("GIOITINH"), Rs.getString("DIACHI"),Rs.getString("SDT"),Rs.getString("CMND"),Rs.getString("CHUCDANH"),Rs.getString("TAIKHOAN"),Rs.getString("MATKHAU"),Rs.getString("GHICHU")};
                defaultTableModel.addRow(objList);                
            }
        } catch (SQLException ex) {
            Logger.getLogger(FormBanHang.class.getName()).log(Level.SEVERE,null,ex);
        }
    }//GEN-LAST:event_tatCaCheckBoxMouseClicked

    private void hoaDonButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hoaDonButtonActionPerformed
        // TODO add your handling code here:
        new FormHoaDon().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_hoaDonButtonActionPerformed

    private void sanPhamButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sanPhamButtonActionPerformed
        // TODO add your handling code here:
        new FormSanPham().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_sanPhamButtonActionPerformed

    private void nhapHangButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nhapHangButtonActionPerformed
        // TODO add your handling code here:
        new FormDonNhapHang().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_nhapHangButtonActionPerformed

    private void khachHangButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_khachHangButtonActionPerformed
        // TODO add your handling code here:
        new FormKhachHang().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_khachHangButtonActionPerformed

    private void nhaCungCapButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nhaCungCapButtonActionPerformed
        // TODO add your handling code here:
        new FormNhaCungCap().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_nhaCungCapButtonActionPerformed

    private void dangXuatButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dangXuatButtonActionPerformed
        // TODO add your handling code here:
        new FormDangNhap().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_dangXuatButtonActionPerformed

    private void baoCaoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baoCaoButtonActionPerformed
        // TODO add your handling code here:
        new FormBaoCao().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_baoCaoButtonActionPerformed

    private void adminCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminCheckBoxActionPerformed
        // TODO add your handling code here:
        try {           
            Connection Con = JDBCConnection.getJDBCConnection();
            PreparedStatement Pst = Con.prepareStatement("select * from nhanvien where CHUCDANH like N'%Admin%'");
            ResultSet Rs = Pst.executeQuery();
            defaultTableModel = (DefaultTableModel)nhanVienTable.getModel();
            defaultTableModel.setRowCount(0);
            while (Rs.next()) {
                Object objList[] = {Rs.getString("MANV"), Rs.getString("TENNV"), Rs.getDate("NGAYSINH"), Rs.getString("GIOITINH"), Rs.getString("DIACHI"),Rs.getString("SDT"),Rs.getString("CMND"),Rs.getString("CHUCDANH"),Rs.getString("TAIKHOAN"),Rs.getString("MATKHAU"),Rs.getString("GHICHU")};
                defaultTableModel.addRow(objList);                
            }
        } catch (SQLException ex) {
            Logger.getLogger(FormBanHang.class.getName()).log(Level.SEVERE,null,ex);
        }
    }//GEN-LAST:event_adminCheckBoxActionPerformed

    private void nhanVienCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nhanVienCheckBoxActionPerformed
        // TODO add your handling code here:
        try {           
            Connection Con = JDBCConnection.getJDBCConnection();
            PreparedStatement Pst = Con.prepareStatement("select * from nhanvien where CHUCDANH like N'%Nhân viên%'");
            ResultSet Rs = Pst.executeQuery();
            defaultTableModel = (DefaultTableModel)nhanVienTable.getModel();
            defaultTableModel.setRowCount(0);
            while (Rs.next()) {
                Object objList[] = {Rs.getString("MANV"), Rs.getString("TENNV"), Rs.getDate("NGAYSINH"), Rs.getString("GIOITINH"), Rs.getString("DIACHI"),Rs.getString("SDT"),Rs.getString("CMND"),Rs.getString("CHUCDANH"),Rs.getString("TAIKHOAN"),Rs.getString("MATKHAU"),Rs.getString("GHICHU")};
                defaultTableModel.addRow(objList);                
            }
        } catch (SQLException ex) {
            Logger.getLogger(FormBanHang.class.getName()).log(Level.SEVERE,null,ex);
        }
    }//GEN-LAST:event_nhanVienCheckBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormNhanVien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox adminCheckBox;
    private javax.swing.JButton baoCaoButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel chucDanhLabel;
    private javax.swing.JButton dangXuatButton;
    private javax.swing.JButton hoaDonButton;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton khachHangButton;
    private javax.swing.JButton nhaCungCapButton;
    private javax.swing.JButton nhanVienButton;
    private javax.swing.JCheckBox nhanVienCheckBox;
    private javax.swing.JLabel nhanVienLabel;
    private javax.swing.JTable nhanVienTable;
    private javax.swing.JButton nhapHangButton;
    private javax.swing.JButton refreshButton;
    private javax.swing.JButton sanPhamButton;
    private javax.swing.JButton suaButton;
    private javax.swing.JCheckBox tatCaCheckBox;
    private javax.swing.JButton themButton;
    private javax.swing.JLabel timKiemLabel;
    private javax.swing.JTextField timKiemTextField;
    private javax.swing.JButton xoaButton;
    // End of variables declaration//GEN-END:variables
}
