/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package A02_BanHang;
import java.awt.print.PrinterException;




/**
 *
 * @author ADMIN
 */
public class PrintHoaDon extends javax.swing.JFrame {
    

    /**
     * Creates new form PrintHoaDon
     */
    public PrintHoaDon() {
        
        initComponents();
        Print();
        
    }
    
    public void Print(){
        HoaDonTex.setText(HoaDonTex.getText()+FormBanHang.ngay+"\t"+FormBanHang.gio+"\n"+
                "\t\t\t      SUPERMAKET\n"+
                "\t\t                    Địa chỉ Trường DH Xây Dựng\n"+
                "\t\t                               SDT: 0353090996\n"+
                "\t\t                            HÓA ĐƠN BÁN HÀNG\n"+
                "\t\t                               Số Hóa đơn: "+FormBanHang.maHoaDon+"\n\n"+
                "Khách hàng: "+FormBanHang.tenKH+"\n"+
                "____________________________________________________________________________________________\n"+
                "Tên hàng hóa\t\t              Đơn giá\t\t         Số lượng\t\t         Thành tiền\n"+
                "____________________________________________________________________________________________\n");
        
        for (int i = 0; i < FormBanHang.row; i++) {
            
            
            if (FormBanHang.tenSP[i].length()<=12)
            {
            HoaDonTex.setText(HoaDonTex.getText()+FormBanHang.tenSP[i]+"\t\t              "+FormBanHang.giaBan[i]+"\t\t        "+FormBanHang.soLuong[i]+"\t\t        "+FormBanHang.thanhTien[i]+"\n"+
                    ".....................................................................................................................................................................................................................\n");           
            
            }else
            {
            HoaDonTex.setText(HoaDonTex.getText()+FormBanHang.tenSP[i]+"\t              "+FormBanHang.giaBan[i]+"\t\t        "+FormBanHang.soLuong[i]+"\t\t        "+FormBanHang.thanhTien[i]+"\n"+
                    ".....................................................................................................................................................................................................................\n");           
            }  
            
        }
        HoaDonTex.setText(HoaDonTex.getText()+
                "\t\t\t\t\tTổng tiền hàng:               "+FormBanHang.tongTien+"\n\n\n"+
                "\t\t\t  Cám ơn và hẹn gặp lại!");
        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        HoaDonTex = new javax.swing.JTextArea();
        InBtn = new javax.swing.JButton();
        HuyBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        HoaDonTex.setEditable(false);
        HoaDonTex.setColumns(20);
        HoaDonTex.setRows(5);
        jScrollPane1.setViewportView(HoaDonTex);

        InBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        InBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/A00_Icon/Print.png"))); // NOI18N
        InBtn.setText("In");
        InBtn.setPreferredSize(new java.awt.Dimension(120, 40));
        InBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InBtnMouseClicked(evt);
            }
        });
        InBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InBtnActionPerformed(evt);
            }
        });

        HuyBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        HuyBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/A00_Icon/Delete.png"))); // NOI18N
        HuyBtn.setText("Đóng");
        HuyBtn.setPreferredSize(new java.awt.Dimension(120, 40));
        HuyBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HuyBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(InBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(HuyBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 665, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 627, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(HuyBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void InBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InBtnMouseClicked
        // TODO add your handling code here:
        try {
            HoaDonTex.print();
        } catch (PrinterException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_InBtnMouseClicked

    private void HuyBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HuyBtnMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_HuyBtnMouseClicked

    private void InBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea HoaDonTex;
    private javax.swing.JButton HuyBtn;
    private javax.swing.JButton InBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
