/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package A06_NhaCungCap;


import A00_Connection.JDBCConnection;
import A02_BanHang.FormBanHang;
import A01_DangNhap.FormDangNhap;
import A11_BaoCao.FormBaoCao;
import A03_SanPham.FormSanPham;
import A07_HoaDon.FormHoaDon;
import A05_KhachHang.FormKhachHang;
import A04_NhanVien.FormNhanVien;
import A09_DonNhapHang.FormDonNhapHang;
import java.awt.Font;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author ADMIN
 */
public class FormNhaCungCap extends javax.swing.JFrame {
    NhaCungCapService nhaCungCapService;
    DefaultTableModel defaultTableModel;

    /**
     * Creates new form FormNhanVien
     */
    public FormNhaCungCap() {
        initComponents();
        nhaCungCapService = new NhaCungCapService();
        defaultTableModel = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; //To change body of generated methods, choose Tools | Templates.
            }
            
        };
        
        nhaCungCapTable.setModel(defaultTableModel);
        
        defaultTableModel.addColumn("Mã Nhà Cung Cấp");
        defaultTableModel.addColumn("Tên Nhà Cung Cấp");
        defaultTableModel.addColumn("Địa Chỉ");
        defaultTableModel.addColumn("Số Điện Thoại");
        defaultTableModel.addColumn("Ghi Chú");
        nhaCungCapTable.setRowHeight(24);
        nhaCungCapTable.setFont(new Font("Segoe UI",Font.PLAIN,18));
        nhaCungCapTable.getTableHeader().setFont(new Font("Segoe",Font.BOLD,18));
        setTableData(nhaCungCapService.getAllNhaCungCaps());
    }
    private void setTableData(List<NhaCungCap> nhaCungCaps){
        for(NhaCungCap nhaCungCap : nhaCungCaps){
            defaultTableModel.addRow(new Object[]{nhaCungCap.getMANCC(), nhaCungCap.getTENNCC(),nhaCungCap.getDIACHI(), nhaCungCap.getSDT(),
            nhaCungCap.getGHICHU()});                  
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem2 = new javax.swing.JCheckBoxMenuItem();
        jPanel2 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        sanPhamButton = new javax.swing.JButton();
        hoaDonButton = new javax.swing.JButton();
        nhapHangButton = new javax.swing.JButton();
        nhanVienButton = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        khachHangButton = new javax.swing.JButton();
        dangXuatButton = new javax.swing.JButton();
        nhaCungCapButton = new javax.swing.JButton();
        timKiemTextField = new javax.swing.JTextField();
        refreshButton = new javax.swing.JButton();
        themButton = new javax.swing.JButton();
        nhaCungCapLabel = new javax.swing.JLabel();
        xoaButton = new javax.swing.JButton();
        suaButton = new javax.swing.JButton();
        timKiemLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        nhaCungCapTable = new javax.swing.JTable();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jCheckBoxMenuItem2.setSelected(true);
        jCheckBoxMenuItem2.setText("jCheckBoxMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setUndecorated(true);
        setSize(new java.awt.Dimension(1508, 668));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setPreferredSize(new java.awt.Dimension(1508, 668));

        jPanel8.setBackground(new java.awt.Color(102, 255, 0));
        jPanel8.setPreferredSize(new java.awt.Dimension(1508, 80));

        sanPhamButton.setBackground(new java.awt.Color(102, 255, 102));
        sanPhamButton.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        sanPhamButton.setForeground(new java.awt.Color(51, 51, 51));
        sanPhamButton.setText("Sản Phẩm");
        sanPhamButton.setPreferredSize(new java.awt.Dimension(170, 50));
        sanPhamButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sanPhamButtonActionPerformed(evt);
            }
        });

        hoaDonButton.setBackground(new java.awt.Color(102, 255, 102));
        hoaDonButton.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        hoaDonButton.setForeground(new java.awt.Color(51, 51, 51));
        hoaDonButton.setText("Hóa Đơn");
        hoaDonButton.setPreferredSize(new java.awt.Dimension(170, 50));
        hoaDonButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hoaDonButtonActionPerformed(evt);
            }
        });

        nhapHangButton.setBackground(new java.awt.Color(102, 255, 102));
        nhapHangButton.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        nhapHangButton.setForeground(new java.awt.Color(51, 51, 51));
        nhapHangButton.setText("Nhập Hàng");
        nhapHangButton.setPreferredSize(new java.awt.Dimension(170, 50));
        nhapHangButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nhapHangButtonActionPerformed(evt);
            }
        });

        nhanVienButton.setBackground(new java.awt.Color(102, 255, 102));
        nhanVienButton.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        nhanVienButton.setForeground(new java.awt.Color(51, 51, 51));
        nhanVienButton.setText("Nhân Viên");
        nhanVienButton.setPreferredSize(new java.awt.Dimension(170, 50));
        nhanVienButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nhanVienButtonActionPerformed(evt);
            }
        });

        jButton10.setBackground(new java.awt.Color(102, 255, 102));
        jButton10.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jButton10.setForeground(new java.awt.Color(51, 51, 51));
        jButton10.setText("Báo Cáo");
        jButton10.setPreferredSize(new java.awt.Dimension(170, 50));
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        khachHangButton.setBackground(new java.awt.Color(102, 255, 102));
        khachHangButton.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        khachHangButton.setForeground(new java.awt.Color(51, 51, 51));
        khachHangButton.setText("Khách Hàng");
        khachHangButton.setPreferredSize(new java.awt.Dimension(170, 50));
        khachHangButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                khachHangButtonActionPerformed(evt);
            }
        });

        dangXuatButton.setBackground(new java.awt.Color(102, 255, 102));
        dangXuatButton.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        dangXuatButton.setForeground(new java.awt.Color(51, 51, 51));
        dangXuatButton.setText("Đăng Xuất");
        dangXuatButton.setToolTipText("");
        dangXuatButton.setPreferredSize(new java.awt.Dimension(170, 50));
        dangXuatButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dangXuatButtonActionPerformed(evt);
            }
        });

        nhaCungCapButton.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        nhaCungCapButton.setText("Nhà Cung Cấp");
        nhaCungCapButton.setPreferredSize(new java.awt.Dimension(170, 50));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sanPhamButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(nhanVienButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(khachHangButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(hoaDonButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(nhaCungCapButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(nhapHangButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(dangXuatButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sanPhamButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(nhanVienButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(khachHangButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(hoaDonButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(nhaCungCapButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(nhapHangButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(dangXuatButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        timKiemTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        timKiemTextField.setPreferredSize(new java.awt.Dimension(350, 40));
        timKiemTextField.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                timKiemTextFieldCaretUpdate(evt);
            }
        });
        timKiemTextField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                timKiemTextFieldMouseClicked(evt);
            }
        });
        timKiemTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timKiemTextFieldActionPerformed(evt);
            }
        });

        refreshButton.setBackground(new java.awt.Color(0, 255, 0));
        refreshButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        refreshButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/A00_Icon/Refresh.png"))); // NOI18N
        refreshButton.setText("Refresh");
        refreshButton.setPreferredSize(new java.awt.Dimension(120, 40));
        refreshButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshButtonActionPerformed(evt);
            }
        });

        themButton.setBackground(new java.awt.Color(0, 255, 0));
        themButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        themButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/A00_Icon/Add.png"))); // NOI18N
        themButton.setText("Thêm ");
        themButton.setPreferredSize(new java.awt.Dimension(120, 40));
        themButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                themButtonActionPerformed(evt);
            }
        });

        nhaCungCapLabel.setBackground(new java.awt.Color(60, 63, 100));
        nhaCungCapLabel.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        nhaCungCapLabel.setForeground(new java.awt.Color(51, 51, 51));
        nhaCungCapLabel.setText("Nhà Cung Cấp");
        nhaCungCapLabel.setPreferredSize(new java.awt.Dimension(170, 40));

        xoaButton.setBackground(new java.awt.Color(0, 255, 0));
        xoaButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        xoaButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/A00_Icon/icons8-delete-bin-32.png"))); // NOI18N
        xoaButton.setText("Xóa");
        xoaButton.setPreferredSize(new java.awt.Dimension(120, 40));
        xoaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xoaButtonActionPerformed(evt);
            }
        });

        suaButton.setBackground(new java.awt.Color(0, 255, 0));
        suaButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        suaButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/A00_Icon/Edit.png"))); // NOI18N
        suaButton.setText("Sửa");
        suaButton.setPreferredSize(new java.awt.Dimension(120, 40));
        suaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suaButtonActionPerformed(evt);
            }
        });

        timKiemLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        timKiemLabel.setText("Tìm kiếm ");
        timKiemLabel.setPreferredSize(new java.awt.Dimension(80, 40));

        nhaCungCapTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        nhaCungCapTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(nhaCungCapTable);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1506, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(suaButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(refreshButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(nhaCungCapLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(timKiemLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(timKiemTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(themButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(xoaButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1293, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(xoaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(themButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(timKiemTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(timKiemLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(nhaCungCapLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(refreshButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(suaButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void themButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_themButtonActionPerformed
        // TODO add your handling code here:
        new AddNhaCungCap().setVisible(true);
       
    }//GEN-LAST:event_themButtonActionPerformed

    private void refreshButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshButtonActionPerformed
        // TODO add your handling code here:
        defaultTableModel.setRowCount(0);
        setTableData(nhaCungCapService.getAllNhaCungCaps());
    }//GEN-LAST:event_refreshButtonActionPerformed

    private void xoaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xoaButtonActionPerformed
        // TODO add your handling code here:
        int row = nhaCungCapTable.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(FormNhaCungCap.this, "Vui lòng chọn Nhà Cung Cấp cần xóa","Lỗi", JOptionPane.ERROR_MESSAGE);
        }else{
            int confirm = JOptionPane.showConfirmDialog(FormNhaCungCap.this, "Bạn chắc chắn muốn xóa không?");
            
            if (confirm == JOptionPane.YES_OPTION) {
                String MANCC = String.valueOf( nhaCungCapTable.getValueAt(row, 0));
                
                nhaCungCapService.deleteNhaCungCap(MANCC);
                
                defaultTableModel.setRowCount(0);
                setTableData(nhaCungCapService.getAllNhaCungCaps());
            }
        }
    }//GEN-LAST:event_xoaButtonActionPerformed

    private void suaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suaButtonActionPerformed
        // TODO add your handling code here:
        int row = nhaCungCapTable.getSelectedRow();
        if (row == -1) {
            JOptionPane.showMessageDialog(FormNhaCungCap.this, "Vui lòng chọn Nhà Cung Cấp cần sửa","Lỗi", JOptionPane.ERROR_MESSAGE);
        }else{                      
            String MANCC = String.valueOf(nhaCungCapTable.getValueAt(row, 0));
                
            
            new EditNhaCungCap(MANCC).setVisible(true);
        }
    }//GEN-LAST:event_suaButtonActionPerformed

    private void timKiemTextFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_timKiemTextFieldMouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_timKiemTextFieldMouseClicked

    private void timKiemTextFieldCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_timKiemTextFieldCaretUpdate
        // TODO add your handling code here:
        try {           
            Connection Con = JDBCConnection.getJDBCConnection();
            PreparedStatement Pst = Con.prepareStatement("select * from nhacungcap where TENNCC like N'%"+timKiemTextField.getText()+"%' or MANCC like N'%"+timKiemTextField.getText()+"%'");
            ResultSet Rs = Pst.executeQuery();
            defaultTableModel = (DefaultTableModel)nhaCungCapTable.getModel();
            defaultTableModel.setRowCount(0);
            while (Rs.next()) {
                Object objList[] = {Rs.getString("MANCC"), Rs.getString("TENNCC"), Rs.getString("DIACHI"), Rs.getString("SDT"), Rs.getString("GHICHU")};
                defaultTableModel.addRow(objList);                
            }
        } catch (SQLException ex) {
            Logger.getLogger(FormBanHang.class.getName()).log(Level.SEVERE,null,ex);
        }
    }//GEN-LAST:event_timKiemTextFieldCaretUpdate

    private void sanPhamButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sanPhamButtonActionPerformed
        // TODO add your handling code here:
        new FormSanPham().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_sanPhamButtonActionPerformed

    private void hoaDonButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hoaDonButtonActionPerformed
        // TODO add your handling code here:
        new FormHoaDon().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_hoaDonButtonActionPerformed

    private void nhapHangButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nhapHangButtonActionPerformed
        // TODO add your handling code here:
        new FormDonNhapHang().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_nhapHangButtonActionPerformed

    private void nhanVienButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nhanVienButtonActionPerformed
        // TODO add your handling code here:
        new FormNhanVien().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_nhanVienButtonActionPerformed

    private void khachHangButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_khachHangButtonActionPerformed
        // TODO add your handling code here:
        new FormKhachHang().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_khachHangButtonActionPerformed

    private void dangXuatButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dangXuatButtonActionPerformed
        // TODO add your handling code here:
        new FormDangNhap().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_dangXuatButtonActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        new FormBaoCao().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void timKiemTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timKiemTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_timKiemTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormNhaCungCap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormNhaCungCap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormNhaCungCap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormNhaCungCap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormNhaCungCap().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton dangXuatButton;
    private javax.swing.JButton hoaDonButton;
    private javax.swing.JButton jButton10;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton khachHangButton;
    private javax.swing.JButton nhaCungCapButton;
    private javax.swing.JLabel nhaCungCapLabel;
    private javax.swing.JTable nhaCungCapTable;
    private javax.swing.JButton nhanVienButton;
    private javax.swing.JButton nhapHangButton;
    private javax.swing.JButton refreshButton;
    private javax.swing.JButton sanPhamButton;
    private javax.swing.JButton suaButton;
    private javax.swing.JButton themButton;
    private javax.swing.JLabel timKiemLabel;
    private javax.swing.JTextField timKiemTextField;
    private javax.swing.JButton xoaButton;
    // End of variables declaration//GEN-END:variables
}
