/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package A10_ChiTietDonNhapHang;

import A00_Connection.JDBCConnection;
import A03_SanPham.SanPham;
import A03_SanPham.SanPhamService;
import A05_KhachHang.FormKhachHang;
import A09_DonNhapHang.DonNhapHang;
import A09_DonNhapHang.DonNhapHangService;
import java.awt.Font;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ADMIN
 */
public class FormChiTietDonNhapHang extends javax.swing.JFrame {

    DonNhapHang donNhapHang = new DonNhapHang();
    SanPham sanPham = new SanPham();
    ChiTietDonNhapHang chiTietDonNhapHang =new ChiTietDonNhapHang();
    DonNhapHangService donNhapHangService = new DonNhapHangService();
    SanPhamService sanPhamService = new SanPhamService();
    ChiTietDonNhapHangService chiTietDonNhapHangService = new ChiTietDonNhapHangService();
    DefaultTableModel defaultTableModel = new DefaultTableModel();
    /**
     * Creates new form FormChiTietHoaDon
     */
    public FormChiTietDonNhapHang(String MADNH) {
        
        initComponents();
        
        donNhapHang = donNhapHangService.getDonNhapHangByMADNH(MADNH);
        maNHTextField.setText(donNhapHang.getMADNH());
        thoiGianTextField.setText(donNhapHang.getTHOIGIAN().toString());                         
        maNCCTextField.setText(donNhapHang.getMANCC());
        tongTienTextField.setText(String.valueOf(donNhapHang.getTONGTIEN()));
        ghiChuTextField.setText(donNhapHang.getGHICHU());
        defaultTableModel = new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }  
        };
        //chiTietHoaDon = bllcthd.getCTHDByMaHD(MaHD);
        chiTietDonNhapHangTable.setModel(defaultTableModel);
        defaultTableModel.addColumn("Mã Sản Phẩm");
        defaultTableModel.addColumn("Tên Sản Phẩm");
        defaultTableModel.addColumn("Giá Nhập");
        defaultTableModel.addColumn("Số Lượng");
        defaultTableModel.addColumn("Thành Tiền");
        chiTietDonNhapHangTable.setRowHeight(24);
        chiTietDonNhapHangTable.setFont(new Font("Segoe UI",Font.PLAIN,18));
        chiTietDonNhapHangTable.getTableHeader().setFont(new Font("Segoe",Font.BOLD,18));
        SetData(MADNH);
    }
    
    public void SetData(String MADNH){
        try {           
            Connection Con = JDBCConnection.getJDBCConnection();
            PreparedStatement Pst = Con.prepareStatement
            ("select chitietdonnhaphang.MASP,TENSP,chitietdonnhaphang.SOLUONG,chitietdonnhaphang.GIANHAP,(chitietdonnhaphang.SOLUONG*chitietdonnhaphang.GIANHAP) as THANHTIEN "
            + "from chitietdonnhaphang join sanpham on chitietdonnhaphang.MASP=sanpham.MASP "
            + "where MADNH = '"+MADNH+"'");
            ResultSet Rs = Pst.executeQuery();
            
            defaultTableModel.setRowCount(0);
            while (Rs.next()) {
                sanPham = sanPhamService.getSanPhamByMASP(Rs.getString("MASP"));
                Object objList[] = {Rs.getString("MASP"),Rs.getString("TENSP"),Rs.getString("GIANHAP"),Rs.getString("SOLUONG"),Rs.getDouble("THANHTIEN")};
                defaultTableModel.addRow(objList);                
            }
        } catch (SQLException ex) {
            Logger.getLogger(FormKhachHang.class.getName()).log(Level.SEVERE,null,ex);
        }
          
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        chiTietNhapHangLabel = new javax.swing.JLabel();
        dongButton = new javax.swing.JButton();
        maNHTextField = new javax.swing.JTextField();
        maNHLabel = new javax.swing.JLabel();
        thoiGianLabel = new javax.swing.JLabel();
        thoiGianTextField = new javax.swing.JTextField();
        maNCCLabel = new javax.swing.JLabel();
        maNCCTextField = new javax.swing.JTextField();
        tongTienLabel = new javax.swing.JLabel();
        tongTienTextField = new javax.swing.JTextField();
        ghiChuLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ghiChuTextField = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        chiTietDonNhapHangTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setSize(new java.awt.Dimension(1000, 800));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 800));

        jPanel2.setBackground(new java.awt.Color(102, 255, 0));
        jPanel2.setPreferredSize(new java.awt.Dimension(1000, 80));

        chiTietNhapHangLabel.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        chiTietNhapHangLabel.setForeground(new java.awt.Color(51, 51, 51));
        chiTietNhapHangLabel.setText("Chi Tiết Nhập Hàng");

        dongButton.setBackground(new java.awt.Color(0, 255, 0));
        dongButton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        dongButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/A00_Icon/Delete.png"))); // NOI18N
        dongButton.setText("Đóng");
        dongButton.setPreferredSize(new java.awt.Dimension(120, 40));
        dongButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dongButtonMouseClicked(evt);
            }
        });
        dongButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dongButtonActionPerformed(evt);
            }
        });
        dongButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                dongButtonKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(chiTietNhapHangLabel)
                .addGap(194, 194, 194)
                .addComponent(dongButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chiTietNhapHangLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(dongButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        maNHTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        maNHTextField.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        maNHTextField.setEnabled(false);
        maNHTextField.setPreferredSize(new java.awt.Dimension(200, 40));

        maNHLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        maNHLabel.setText("Mã Nhập Hàng");
        maNHLabel.setPreferredSize(new java.awt.Dimension(170, 40));

        thoiGianLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        thoiGianLabel.setText("Thời Gian");
        thoiGianLabel.setPreferredSize(new java.awt.Dimension(170, 40));

        thoiGianTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        thoiGianTextField.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        thoiGianTextField.setEnabled(false);
        thoiGianTextField.setPreferredSize(new java.awt.Dimension(200, 40));

        maNCCLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        maNCCLabel.setText("Mã Nhà Cung Cấp");
        maNCCLabel.setPreferredSize(new java.awt.Dimension(170, 40));

        maNCCTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        maNCCTextField.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        maNCCTextField.setEnabled(false);
        maNCCTextField.setPreferredSize(new java.awt.Dimension(200, 40));

        tongTienLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tongTienLabel.setText("Tổng Tiền");
        tongTienLabel.setPreferredSize(new java.awt.Dimension(170, 40));

        tongTienTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tongTienTextField.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        tongTienTextField.setEnabled(false);
        tongTienTextField.setPreferredSize(new java.awt.Dimension(200, 40));

        ghiChuLabel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ghiChuLabel.setText("Ghi Chú");
        ghiChuLabel.setPreferredSize(new java.awt.Dimension(170, 40));

        ghiChuTextField.setBackground(new java.awt.Color(240, 240, 240));
        ghiChuTextField.setColumns(20);
        ghiChuTextField.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ghiChuTextField.setRows(5);
        ghiChuTextField.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        ghiChuTextField.setEnabled(false);
        jScrollPane1.setViewportView(ghiChuTextField);

        chiTietDonNhapHangTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        chiTietDonNhapHangTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane3.setViewportView(chiTietDonNhapHangTable);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(maNHLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(thoiGianLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ghiChuLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(thoiGianTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(maNHTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tongTienLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(maNCCLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(maNCCTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tongTienTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1))
                .addGap(77, 77, 77))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 998, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(maNHLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maNCCLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maNHTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maNCCTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(thoiGianTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(thoiGianLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tongTienLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tongTienTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ghiChuLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        ghiChuLabel.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void dongButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dongButtonKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_dongButtonKeyPressed

    private void dongButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dongButtonMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_dongButtonMouseClicked

    private void dongButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dongButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dongButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable chiTietDonNhapHangTable;
    private javax.swing.JLabel chiTietNhapHangLabel;
    private javax.swing.JButton dongButton;
    private javax.swing.JLabel ghiChuLabel;
    private javax.swing.JTextArea ghiChuTextField;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel maNCCLabel;
    private javax.swing.JTextField maNCCTextField;
    private javax.swing.JLabel maNHLabel;
    private javax.swing.JTextField maNHTextField;
    private javax.swing.JLabel thoiGianLabel;
    private javax.swing.JTextField thoiGianTextField;
    private javax.swing.JLabel tongTienLabel;
    private javax.swing.JTextField tongTienTextField;
    // End of variables declaration//GEN-END:variables
}
